### ISSUE TITLE
`No module named 'autoapi'` when building through ReadTheDocs

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1034]
**Operating System and version**
ReadTheDocs builder (https://readthedocs.org/projects/py-ipv8/builds/14387369/)

**Traceback and/or steps to reproduce**

```python
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-ipv8/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'autoapi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-ipv8/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-ipv8/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-ipv8/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/py-ipv8/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension autoapi.extension (exception: No module named 'autoapi')

Extension error:
Could not import extension autoapi.extension (exception: No module named 'autoapi')
```

**Comment by qstokkink** [comment]
It seems that adding `sphinx-autoapi` to `requirements.txt` would solve this. That said, this is not a necessary dependency for all other IPv8 use.

Perhaps we should make a separate `requirements_docs.txt` or `doc/requirements.txt` for building docs?

**Comment by qstokkink** [comment]
According to the ReadTheDocs docs we should use an additional config file (`.readthedocs.yaml`) and an additional requirements file (`doc/requirements.txt`) to configure this extra dependency:
https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file
