### ISSUE TITLE
Enhance error message when there is no `community_id` in a community

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#1061]
When one forgets to add a `community_id` to a `Community` subclass, the following error is raised when initializing the community:

```
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/tribler/src/tribler-core/tribler_core/utilities/tiny_tribler_service.py", line 45, in start_tribler
    await self.on_tribler_started()
  File "/Users/martijndevos/Documents/tribler/experiment/popularity_community/crawl_torrents.py", line 229, in on_tribler_started
    session.remote_query_community = TorrentCrawler(peer, ipv8.endpoint, ipv8.network, mds)
  File "/Users/martijndevos/Documents/tribler/experiment/popularity_community/crawl_torrents.py", line 111, in __init__
    super().__init__(my_peer, endpoint, network, rqc_settings=RemoteQueryCommunitySettings(),
  File "/Users/martijndevos/Documents/tribler/src/tribler-core/tribler_core/components/metadata_store/remote_query_community/remote_query_community.py", line 133, in __init__
    super().__init__(my_peer, endpoint, network=network, **kwargs)
  File "/Users/martijndevos/Documents/tribler/src/tribler-core/tribler_core/components/ipv8/tribler_community.py", line 11, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/community.py", line 45, in __init__
    self.endpoint.add_prefix_listener(self, self._prefix)
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/messaging/interfaces/dispatcher/endpoint.py", line 104, in add_prefix_listener
    interface.add_prefix_listener(listener, prefix)
  File "/Users/martijndevos/Documents/tribler/src/pyipv8/ipv8/messaging/interfaces/endpoint.py", line 49, in add_prefix_listener
    raise RuntimeError("Tried to register a prefix of length %d, required to be of length %d!"
RuntimeError: Tried to register a prefix of length 2, required to be of length 22!
```

It took me a bit of time to figure out that this was because I forgot to add the `community_id`. It would be helpful to improve this error message, e.g., by adding a check to see if the `community_id` has been set before registering the prefix.

**Comment by qstokkink** [comment]
Technically, IPv8 does not enforce any `community_id` length (20 bytes is just a convention). Therefore, with our current default of `b''` in the `Community` class, we have no way of detecting an unset `community_id`.

To provide more info, we could set the default value for `Community.community_id` to `None` to detect this (using `assert self.community_id is not None` before [using the prefix](https://github.com/Tribler/py-ipv8/blob/cd9f2809ba80f04854217383d4e79c6236a46579/ipv8/community.py#L43)). The downside of this is that you now need more code to use a `Community` without an id. However, I don't think anyone uses id-less Communities anyway.

**Comment by devos50** [comment]
> To provide more info, we could set the default value for Community.community_id to None to detect this (using assert self.community_id is not None before using the prefix)

Sounds like a good solution to me 👍

**Comment by qstokkink** [comment]
Perhaps a rephrasing would work after all. @devos50 would this f-string work for you?

```python
f"Tried to register {listener} with the prefix {repr(prefix)} of length {len(prefix)}, required to be of length {self.prefixlen}!"
```
