### ISSUE TITLE
List index out of range exception from anonymization community

### ISSUE THREAD

**Issue by ichorid** [Tribler/py-ipv8#110]
Leecher errors, when trying to download through exit node (1 hop). Download does not work.
```
ERROR:TriblerTunnelCommunity:Exception occurred while handling packet!
Traceback (most recent call last):
  File "/mnt/leecher/tribler/Tribler/pyipv8/ipv8/deprecated/community.py", line 283, in on_packet
    self.decode_map[data[22]](source_address, data)
  File "/mnt/leecher/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 767, in on_cell
    message_type = [k for k, v in message_to_payload.iteritems() if v[0] == payload.message_type][0]
IndexError: list index out of range
```
Tunnel helper (exit node) errors:
```
WARNING 1524131154.26       community:976   Got exception InvalidTag() when trying to decrypt relay message: "\x00\x00\x00\x00\x00\x00\x00\x020000000000000000\x02\x00\x0btest1.local\x1b9\x01\x00\x00\x00\x00\x00\x00\x00\x00\x04\x17'\x10\x19\x80\x00\x00\x00\x00H\xa9\x7f\x1e" received for circuit_id: 461418816, is_data: 1, 
WARNING 1524131155.27       community:794   Got exception InvalidTag() when trying to decrypt relay message: '\x00\x00\x00\x00\x00\x00\x00\x020000000000000000P\x13g\x106\xb4\x9f-[\x98\xf2\xd0\x0b\x06\rI\xe1\xaa\x89\xad\xb1\xb5' received for circuit_id: 1606279686, is_data: 0, 
WARNING 1524131163.26       community:794   Got exception InvalidTag() when trying to decrypt relay message: '\x00\x00\x00\x00\x00\x00\x00\x020000000000000000\xb3\xda' received for circuit_id: 2585321991, is_data: 0, 
```

The only file that was modified for running the local testnet is `pyipv8/ipv8/deprecated/community.py`:
``` python

_DEFAULT_ADDRESSES = [
    ("10.0.3.4", 10034)
]


_DNS_ADDRESSES = [
]

```

**Comment by ichorid** [comment]
Oops, sorry on that, mismatched versions of Tribler ((
