### ISSUE TITLE
Python 3.11 asynctest support

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1110]
The IPv8 unit tests fail on Python 3.11 due to the `asynctest` dependency.

```python
Traceback (most recent call last):
  File "C:\py-ipv8\run_all_tests.py", line 166, in <module>
    test_class_names = find_all_test_class_names()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\py-ipv8\run_all_tests.py", line 139, in find_all_test_class_names
    test_class_names.extend(derive_test_class_names(found_test))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\py-ipv8\run_all_tests.py", line 126, in derive_test_class_names
    module_instance = importlib.import_module(module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\py-ipv8\ipv8\test\test_community.py", line 1, in <module>
    from .base import TestBase
  File "C:\py-ipv8\ipv8\test\base.py", line 13, in <module>
    import asynctest
  File "C:\Python311\Lib\site-packages\asynctest\__init__.py", line 22, in <module>
    from .case import *
  File "C:\Python311\Lib\site-packages\asynctest\case.py", line 54, in <module>
    import asynctest.selector
  File "C:\Python311\Lib\site-packages\asynctest\selector.py", line 29, in <module>
    from . import mock
  File "C:\Python311\Lib\site-packages\asynctest\mock.py", line 428, in <module>
    class _AwaitEvent:
  File "C:\Python311\Lib\site-packages\asynctest\mock.py", line 433, in _AwaitEvent
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

**Comment by qstokkink** [comment]
It is probably (near) impossible to save `asynctest`. However, our use of `asynctest` is limited to the `TestCase` class and we _should_ be able to switch to [IsolatedAsyncioTestCase](https://docs.python.org/3/library/unittest.html#unittest.IsolatedAsyncioTestCase) for newer versions of Python (i.e., > 3.7).
