### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'execute'

### ISSUE THREAD

**Issue by xoriole** [Tribler/py-ipv8#116]
IPv8 is having problem on shutting down. See the logs:
```python
ERROR   1524667809.84              rest_manager:53   (RESTRequest)  [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'execute'
/usr/lib/python2.7/dist-packages/twisted/protocols/basic.py:571:dataReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1657:lineReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:1736:allContentReceived
/usr/lib/python2.7/dist-packages/twisted/web/http.py:762:requestReceived
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/web/server.py:183:process
/usr/lib/python2.7/dist-packages/twisted/web/server.py:234:render
/usr/lib/python2.7/dist-packages/twisted/web/resource.py:250:render
/home/sandip/tudelft/tribler/Tribler/Core/Modules/restapi/trustchain_endpoint.py:87:render_GET
/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/util.py:14:helper
/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/util.py:26:blockingCallFromThread
/home/sandip/tudelft/tribler/Tribler/community/triblerchain/community.py:44:get_statistics
/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py:80:get_latest
/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py:49:_get
/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/database.py:40:wrapper
/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/database.py:302:execute
]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)
  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/resource.py", line 250, in render
    return m(request)
  File "/home/sandip/tudelft/tribler/Tribler/Core/Modules/restapi/trustchain_endpoint.py", line 87, in render_GET
    return json.dumps({'statistics': triblerchain_community.get_statistics()})
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/util.py", line 14, in helper
    return blockingCallFromThread(reactor, func, *args, **kargs)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/util.py", line 26, in blockingCallFromThread
    return f(*args, **kwargs)
  File "/home/sandip/tudelft/tribler/Tribler/community/triblerchain/community.py", line 44, in get_statistics
    latest_block = self.persistence.get_latest(public_key)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py", line 80, in get_latest
    u"WHERE public_key = ?)", (buffer(public_key), buffer(public_key)))
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py", line 49, in _get
    db_result = list(self.execute(self.get_sql_header() + query, params, fetch_all=False))
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/database.py", line 40, in wrapper
    return f(self, *args, **kwargs)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/database.py", line 302, in execute
    result = self._cursor.execute(statement, bindings)
AttributeError: 'NoneType' object has no attribute 'execute'
```
Similar: Exception while handling packet #103

**Comment by qstokkink** [comment]
Ah, I see a `blockingCallFromThread` in your stacktrace.

**Comment by qstokkink** [comment]
I have seen this error before myself, but I have no way to reliably reproduce this. @xoriole do you have a way to reproduce this reliably?

**Comment by xoriole** [comment]
I've seen this issue at shut down if you had debug pane opened in the background. But it does not always happen.

**Comment by qstokkink** [comment]
@xoriole if that is the only case, it definitely due to the `blockingCallFromThread`.

**Comment by qstokkink** [comment]
Hmm.. actually we want the `Overlay` to register all calls to its `TaskManager` context. If the call gets scheduled after the `Overlay` has already unloaded, it is simply cancelled.
