### ISSUE TITLE
Front-page builders are not triggering automatically

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1253]
After the most recent push to `master`, the "front-page" (`README`) builders did not trigger automatically.

For now, I manually triggered:

https://jenkins-ci.tribler.org/job/ipv8/job/test_ipv8_linux/
https://jenkins-ci.tribler.org/job/ipv8/job/test_ipv8_windows/
https://jenkins-ci.tribler.org/job/ipv8/job/test_ipv8_mac/

This is not really a bug but still wildly annoying so I'll assign it medium priority.

**Comment by qstokkink** [comment]
It appears that the parent job that is supposed to trigger these jobs, `clone_ipv8_git`, has not been triggered. There is probably something wrong with the Jenkins hook configuration.

**Comment by qstokkink** [comment]
There is a stack trace in the hook log:

```
FATAL: hudson.plugins.git.GitException: Command "git ls-remote -h https://github.com/Tribler/py-ipv8/" returned status code 128:
stdout: 
stderr: fatal: could not open '/dev/null' for reading and writing: Operation not permitted

hudson.plugins.git.GitException: Command "git ls-remote -h https://github.com/Tribler/py-ipv8/" returned status code 128:
stdout: 
stderr: fatal: could not open '/dev/null' for reading and writing: Operation not permitted

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2842)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2185)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2079)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2070)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.getHeadRev(CliGitAPIImpl.java:3735)
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWithImpl(GitSCM.java:731)
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:690)
Caused: java.io.IOException
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:692)
	at hudson.scm.SCM.compareRemoteRevisionWith(SCM.java:419)
	at hudson.scm.SCM.poll(SCM.java:436)
	at hudson.model.AbstractProject._poll(AbstractProject.java:1427)
	at hudson.model.AbstractProject.poll(AbstractProject.java:1333)
	at com.cloudbees.jenkins.GitHubPushTrigger$1.runPolling(GitHubPushTrigger.java:125)
	at com.cloudbees.jenkins.GitHubPushTrigger$1.run(GitHubPushTrigger.java:151)
	at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by qstokkink** [comment]
If the root cause is indeed a corrupt `/dev/null`, we can easily repair this by restarting the machine (or restoring `/dev/null` the hard way).

**Comment by qstokkink** [comment]
This is now fixed (see also https://jenkins-ci.tribler.org/job/ipv8/job/clone_ipv8_git/GitHubPollLog/ for the current status).
