### ISSUE TITLE
Attestation/identity validation tests not checking out PR code

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1267]
As shown in #1266, the attestation/identity validation tests seem to be running an old code version. These scripts should run the up-to-date PR code instead.

```python
Traceback (most recent call last):
  File "/home/jenkins/ci/workspace/ipv8/validate_attestation_tutorial/pyipv8/ipv8/REST/rest_manager.py", line 75, in error_middleware
    response = await handler(request)
  File "/home/jenkins/.local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/home/jenkins/ci/workspace/ipv8/validate_attestation_tutorial/pyipv8/ipv8/REST/attestation_endpoint.py", line 320, in handle_post
    key = self.attestation_overlay.get_id_algorithm(id_format).generate_secret_key()
  File "/home/jenkins/ci/workspace/ipv8/validate_attestation_tutorial/pyipv8/ipv8/attestation/wallet/bonehexact/algorithm.py", line 75, in generate_secret_key
    return generate_keypair(self.key_size)[1]
  File "/home/jenkins/ci/workspace/ipv8/validate_attestation_tutorial/pyipv8/ipv8/attestation/wallet/primitives/boneh.py", line 110, in generate_keypair
    t1, t2 = generate_primes(key_size)
  File "/home/jenkins/ci/workspace/ipv8/validate_attestation_tutorial/pyipv8/ipv8/attestation/wallet/primitives/boneh.py", line 102, in generate_primes
    p, q = generate_safe_prime(key_size), generate_safe_prime(key_size)
  File "/home/jenkins/ci/workspace/ipv8/validate_attestation_tutorial/pyipv8/ipv8/attestation/wallet/primitives/cryptography_wrapper.py", line 31, in generate_safe_prime
    backend._lib.BN_clear_free(generated)
AttributeError: module 'lib' has no attribute 'BN_clear_free'
```

**Comment by qstokkink** [comment]
The `GIT_USER` and `GIT_BRANCH` were set to the defaults of `Tribler` and `master`. I hooked the job into the new git plugin's variable names.
