### ISSUE TITLE
Main coverage job failing

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#1297]
See "front page".

On Windows:

```python
Successfully installed coverage-7.5.3
C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\coverage\inorout.py:456: CoverageWarning: --include is ignored because --source is set (include-ignored)
  self.warn("--include is ignored because --source is set", slug="include-ignored")
Traceback (most recent call last):
  File "create_test_coverage_report.py", line 92, in <module>
    analysis = Analysis(cov.get_data(), 0, file_reporter, abs_file)
TypeError: __init__() missing 6 required positional arguments: 'excluded', 'executed', '_arc_possibilities_set', '_arcs_executed_set', 'exit_counts', and 'no_branch'
```

On Mac:

```python
 Traceback (most recent call last):
  File "/Users/runner/work/py-ipv8/py-ipv8/create_test_coverage_report.py", line 45, in <module>
    test_paths = find_all_test_class_names()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/py-ipv8/py-ipv8/run_all_tests.py", line 252, in find_all_test_class_names
    test_class_names.extend(derive_test_class_names(found_test))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/runner/work/py-ipv8/py-ipv8/run_all_tests.py", line 236, in derive_test_class_names
    module_instance = importlib.import_module(module_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/runner/work/py-ipv8/py-ipv8/ipv8/test/test_database.py", line 2, in <module>
    from .base import TestBase
  File "/Users/runner/work/py-ipv8/py-ipv8/ipv8/test/base.py", line 16, in <module>
    from ..lazy_community import PacketDecodingError, lazy_wrapper, lazy_wrapper_unsigned
  File "/Users/runner/work/py-ipv8/py-ipv8/ipv8/lazy_community.py", line 7, in <module>
    from .keyvault.crypto import default_eccrypto
  File "/Users/runner/work/py-ipv8/py-ipv8/ipv8/keyvault/crypto.py", line 9, in <module>
    from .private.libnaclkey import LibNaCLSK
  File "/Users/runner/work/py-ipv8/py-ipv8/ipv8/keyvault/private/libnaclkey.py", line 1, in <module>
    import libnacl
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/libnacl/__init__.py", line 87, in <module>
    nacl = _get_nacl()
           ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/libnacl/__init__.py", line 49, in _get_nacl
    raise OSError(msg)
OSError: Could not locate nacl lib, searched for libsodium
```

**Comment by qstokkink** [comment]
The Mac issue has been solved before, in a different job, as follows:

https://github.com/Tribler/py-ipv8/blob/08a1e08fbbf700435bf118b4058e1799085ff8c4/.github/workflows/unittests.yml#L43

**Comment by qstokkink** [comment]
For the Windows issue, the `Analysis` class seems to be off-limits now and the `analysis_from_file_reporter()` function looks to be its replacement (with the same args).
