### ISSUE TITLE
Race cond in 2hop teardown test

### ISSUE THREAD

**Issue by ichorid** [Tribler/py-ipv8#135]
Probably another race condition, seen only once under #134  
Can't trigger again.
``` python
Check if the reactor thread is properly blocked by a threaded function. ... ok
Check if a blocking call propagates its errors from a thread. ... ok

======================================================================
ERROR: Check if a 2 hop circuit can be destroyed (by the exit node)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/vader/src/TRIBLER/tribler_ichorid/Tribler/pyipv8/ipv8/test/util.py", line 125, in errback
    failure.raiseException()
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/vader/src/TRIBLER/tribler_ichorid/Tribler/pyipv8/ipv8/test/messaging/anonymization/test_community.py", line 153, in test_destroy_circuit_from_exit
    self.nodes[2].overlay.remove_exit_socket(self.nodes[2].overlay.exit_sockets.keys()[0], destroy=True)
IndexError: list index out of range
-------------------- >> begin captured logging << --------------------
twisted: INFO: --> Tribler.pyipv8.ipv8.test.messaging.anonymization.test_community.TestTunnelCommunity.test_destroy_circuit_from_exit <--
TunnelCommunity: DEBUG: Launching TunnelCommunity with prefix 00027d510d1f81f63deaf2020464d1abdf0eb167e02e.
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode = False
TunnelCommunity: DEBUG: Launching TunnelCommunity with prefix 00027d510d1f81f63deaf2020464d1abdf0eb167e02e.
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode = False
TunnelCommunity: DEBUG: Launching TunnelCommunity with prefix 00027d510d1f81f63deaf2020464d1abdf0eb167e02e.
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode = False
TunnelCommunity: INFO: want 1 data circuits of length 2
TunnelCommunity: INFO: Creating a new circuit of length 2 (type: DATA)
TunnelCommunity: INFO: Could not create circuit, no available exit-nodes
TunnelCommunity: INFO: circuit creation of 1 circuits failed, no need to continue
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
```

**Comment by qstokkink** [comment]
It seems the exit node's socket was either (1) never created or (2) already shut down.

What you are seeing is the code responsible for test cleanup not having an exit socket to close.

**Comment by ichorid** [comment]
It happened again:
``` python
Check if a blocking call propagates its errors from a thread. ... ok

======================================================================
ERROR: Check if a 2 hop circuit can be destroyed (by the exit node)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/vader/src/TRIBLER/tribler_ichorid/Tribler/pyipv8/ipv8/test/util.py", line 125, in errback
    failure.raiseException()
  File "/home/vader/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/vader/src/TRIBLER/tribler_ichorid/Tribler/pyipv8/ipv8/test/messaging/anonymization/test_community.py", line 153, in test_destroy_circuit_from_exit
    self.nodes[2].overlay.remove_exit_socket(self.nodes[2].overlay.exit_sockets.keys()[0], destroy=True)
IndexError: list index out of range
-------------------- >> begin captured logging << --------------------
twisted: INFO: --> Tribler.pyipv8.ipv8.test.messaging.anonymization.test_community.TestTunnelCommunity.test_destroy_circuit_from_exit <--
TunnelCommunity: DEBUG: Launching TunnelCommunity with prefix 00027d510d1f81f63deaf2020464d1abdf0eb167e02e.
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode = False
TunnelCommunity: DEBUG: Launching TunnelCommunity with prefix 00027d510d1f81f63deaf2020464d1abdf0eb167e02e.
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode = False
TunnelCommunity: DEBUG: Launching TunnelCommunity with prefix 00027d510d1f81f63deaf2020464d1abdf0eb167e02e.
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode = False
TunnelCommunity: INFO: want 1 data circuits of length 2
TunnelCommunity: INFO: Creating a new circuit of length 2 (type: DATA)
TunnelCommunity: INFO: Could not create circuit, no available exit-nodes
TunnelCommunity: INFO: circuit creation of 1 circuits failed, no need to continue
--------------------- >> end captured logging << ---------------------

```

**Comment by qstokkink** [comment]
I just ran this test 1000 times (not an exaggeration) without being able to reproduce this. The timeout is probably just a little bit too short then for the testing hardware.

**Comment by qstokkink** [comment]
This seems to be caused by `TestBase.introduce_nodes` using `sleep`. If I change the function to the following, I get the same error:

```python
@inlineCallbacks
    def introduce_nodes(self):
        for node in self.nodes:
            node.discovery.take_step()
        #yield self.sleep()
        from twisted.internet.defer import succeed
        yield succeed(None)
```

I'll have to check out whether we can `deliver_messages` here.
