### ISSUE TITLE
TestTrustChainCommunity.test_retrieve_missing_block sometimes does not finish

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#160]
Regardless of the test timeout, the `TestTrustChainCommunity.test_retrieve_missing_block` function may not finish. Here is the output for a timeout of 5 seconds:

```
E
======================================================================
ERROR: Check if missing blocks are retrieved through a crawl request.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/quinten/Documents/py-ipv8/ipv8/test/util.py", line 149, in wrapper
    % timeout)
TimeExpired: timeout expired before end of test (5.000000 s.)
-------------------- >> begin captured stdout << ---------------------








--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
root: INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
twisted: DEBUG: PythonLoggingObserver hooked up
twisted: INFO: --> ipv8.test.attestation.trustchain.test_community.TestTrustChainCommunity.test_retrieve_missing_block <--
TrustChainCommunity: DEBUG: Launching TrustChainCommunity with prefix 00023199e175392a876e8cc7fbcabe5c948eeaeafa23.
TrustChainDB: DEBUG: loading database [:memory:]
TrustChainDB: DEBUG: TrustChain database path: :memory:
TrustChainDB: DEBUG: open database [:memory:]
TrustChainDB: DEBUG: PRAGMA page_size = 8192 (previously: 1024) [:memory:]
TrustChainDB: DEBUG: PRAGMA journal_mode = MEMORY (no change) [:memory:]
TrustChainDB: DEBUG: PRAGMA synchronous = NORMAL (previously: 2) [:memory:]
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: The trustchain community started with Public Key: 4c69624e61434c504b3a6a6819c0e6b8444fc1372cf83e166ca0b00e9a42acc1e78c894928e195f59955cfb20b5bf5b9d5a5665c4a8865b7bb92843eea0f144d28e5615367c307583ad4
TrustChainCommunity: DEBUG: Launching TrustChainCommunity with prefix 00023199e175392a876e8cc7fbcabe5c948eeaeafa23.
TrustChainDB: DEBUG: loading database [:memory:]
TrustChainDB: DEBUG: TrustChain database path: :memory:
TrustChainDB: DEBUG: open database [:memory:]
TrustChainDB: DEBUG: PRAGMA page_size = 8192 (previously: 1024) [:memory:]
TrustChainDB: DEBUG: PRAGMA journal_mode = MEMORY (no change) [:memory:]
TrustChainDB: DEBUG: PRAGMA synchronous = NORMAL (previously: 2) [:memory:]
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: The trustchain community started with Public Key: 4c69624e61434c504b3a4463b6922bfbcbfcdc21fbbc84fbae4f4b013345e85d6d96064a1f138a5d792c65a3706c1b9c8c7a82a3e2a571144a5f4affe5fdf657b3965c047d5add988342
RequestCache: DEBUG: add <IntroCrawlTimeout introcrawltimeout-268617659146100351994572415208718843119997205530>
RequestCache: DEBUG: add <CrawlRequestCache crawl-21922>
TrustChainCommunity: INFO: Requesting crawl of node dd988342:1 with id 21922
RequestCache: DEBUG: add <IntroCrawlTimeout introcrawltimeout-399196206328180203883948668705562098857963905892>
RequestCache: DEBUG: add <CrawlRequestCache crawl-14779>
TrustChainCommunity: INFO: Requesting crawl of node 07583ad4:1 with id 14779
TrustChainCommunity: INFO: Received crawl request from node 07583ad4 for sequence number 1
TrustChainCommunity: DEBUG: Sending block for crawl request to Peer<122.245.35.126:14579, ReyTtYVqw06b+g9B4MTEVPV7Y2Q=> (Block e429e120 from ...dd988342:1 links ...30303030:0 for {})
TrustChainCommunity: INFO: Sent 0 blocks
TrustChainCommunity: INFO: Received crawl request from node dd988342 for sequence number 1
TrustChainCommunity: DEBUG: Sending block for crawl request to Peer<115.113.197.219:40102, Lw07gCSz2ktWdkxGVWD35INKvBo=> (Block 39ba7e35 from ...07583ad4:1 links ...30303030:0 for {})
TrustChainCommunity: INFO: Sent 0 blocks
TrustChainCommunity: DEBUG: Block validation result <function invalid at 0x7f16c46e7de8>, ['Invalid signature', 'Linked public key is not valid'], (Block e429e120 from ...dd988342:1 links ...30303030:0 for {})
TrustChainCommunity: DEBUG: Block validation result <function invalid at 0x7f16c46e7de8>, ['Invalid signature', 'Linked public key is not valid'], (Block 39ba7e35 from ...07583ad4:1 links ...30303030:0 for {})
TrustChainCommunity: INFO: Signed block to dd988342 (Block f5e64fb3 from ...07583ad4:1 links ...dd988342:0 for {}) validation result (<function partial_next at 0x7f16c46e7c80>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to (115.113.197.219:40102) (Block f5e64fb3 from ...07583ad4:1 links ...dd988342:0 for {})
RequestCache: DEBUG: add <HalfBlockSignCache sign-59850801>
TrustChainCommunity: INFO: Signed block to dd988342 (Block cdd3e1c4 from ...07583ad4:2 links ...dd988342:0 for {}) validation result (<function partial_next at 0x7f16c46e7c80>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to (115.113.197.219:40102) (Block cdd3e1c4 from ...07583ad4:2 links ...dd988342:0 for {})
RequestCache: DEBUG: add <HalfBlockSignCache sign-59850802>
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Block validation result <function no_info at 0x7f16c46e7d70>, [], (Block cdd3e1c4 from ...07583ad4:2 links ...dd988342:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block cdd3e1c4 from ...07583ad4:2 links ...dd988342:0 for {})
TrustChainCommunity: INFO: Received request block addressed to us (Block cdd3e1c4 from ...07583ad4:2 links ...dd988342:0 for {})
TrustChainCommunity: INFO: Request block could not be validated sufficiently, crawling requester. (<function no_info at 0x7f16c46e7d70>, [])
RequestCache: DEBUG: add <CrawlRequestCache crawl-21694148>
TrustChainCommunity: INFO: Requesting crawl of node 07583ad4:1 with id 21694148
TrustChainCommunity: INFO: Received crawl request from node dd988342 for sequence number 1
TrustChainCommunity: DEBUG: Sending block for crawl request to Peer<115.113.197.219:40102, Lw07gCSz2ktWdkxGVWD35INKvBo=> (Block f5e64fb3 from ...07583ad4:1 links ...dd988342:0 for {})
TrustChainCommunity: DEBUG: Sending block for crawl request to Peer<115.113.197.219:40102, Lw07gCSz2ktWdkxGVWD35INKvBo=> (Block cdd3e1c4 from ...07583ad4:2 links ...dd988342:0 for {})
TrustChainCommunity: INFO: Sent 2 blocks
TrustChainCommunity: DEBUG: Block validation result <function no_info at 0x7f16c46e7d70>, [], (Block cdd3e1c4 from ...07583ad4:2 links ...dd988342:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block cdd3e1c4 from ...07583ad4:2 links ...dd988342:0 for {})
TrustChainCommunity: INFO: Received request block addressed to us (Block cdd3e1c4 from ...07583ad4:2 links ...dd988342:0 for {})
TrustChainCommunity: INFO: Request block could not be validated sufficiently, crawling requester. (<function no_info at 0x7f16c46e7d70>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Block validation result <function valid at 0x7f16c46e7b90>, [], (Block f5e64fb3 from ...07583ad4:1 links ...dd988342:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block f5e64fb3 from ...07583ad4:1 links ...dd988342:0 for {})
TrustChainCommunity: INFO: Received request block addressed to us (Block f5e64fb3 from ...07583ad4:1 links ...dd988342:0 for {})
TrustChainCommunity: INFO: Signed block to 07583ad4 (Block 25b3d1a9 from ...dd988342:1 links ...07583ad4:1 for {}) validation result (<function partial_next at 0x7f16c46e7c80>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to (122.245.35.126:14579) (Block 25b3d1a9 from ...dd988342:1 links ...07583ad4:1 for {})
TrustChainCommunity: DEBUG: Broadcasting blocks Block f5e64fb3 from ...07583ad4:1 links ...dd988342:0 for {} and Block 25b3d1a9 from ...dd988342:1 links ...07583ad4:1 for {}
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Broadcasting blocks Block f5e64fb3 from ...07583ad4:1 links ...dd988342:0 for {} and Block 25b3d1a9 from ...dd988342:1 links ...07583ad4:1 for {}
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x7f16c46e7c80>, [], (Block 25b3d1a9 from ...dd988342:1 links ...07583ad4:1 for {})
TrustChainCommunity: DEBUG: Received already known block (Block 25b3d1a9 from ...dd988342:1 links ...07583ad4:1 for {})
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 5.075s

FAILED (errors=1)
```

**Comment by qstokkink** [comment]
Confirmed, after the missing piece in the chain is retrieved the sign deferred is never fired:

```
FORMAT:
RECEIVER <- SEQUENCE_NUMBER (SENDER)

GOOD:
69f0 <- 1 (a4f3)
a4f3 <- 1 (69f0)
69f0 <- 2 (a4f3)
69f0 <- 1 (a4f3)
69f0 <- 2 (a4f3)
a4f3 <- 1 (69f0)
a4f3 <- 2 (69f0)

BAD:
6d8c <- 1 (d417)
d417 <- 1 (6d8c)
d417 <- 2 (6d8c)
d417 <- 2 (6d8c)
d417 <- 1 (6d8c)
6d8c <- 1 (d417)
```

**Comment by qstokkink** [comment]
You can reliably trigger the error by sending the packets in reverse order, change:

https://github.com/Tribler/py-ipv8/blob/89217935f3e5e4fc4411f65da98f717de3859f0f/ipv8/attestation/trustchain/community.py#L332-L333

to:
```python
        for ind in reversed(xrange(len(blocks))):
            self.send_crawl_response(blocks[ind], payload.crawl_id, ind + 1, total_count, peer)
            import time
            time.sleep(0.1)
```
