### ISSUE TITLE
exceptions.AttributeError: 'Circuit' object has no attribute 'sock_addr'

### ISSUE THREAD

**Issue by xoriole** [Tribler/py-ipv8#207]
```python
Unhandled Error
Traceback (most recent call last):
  File "/home/sandip/tudelft/tribler/run_tribler.py", line 84, in <module>
    start_tribler_core(base_path, api_port)
  File "/home/sandip/tudelft/tribler/run_tribler.py", line 76, in start_tribler_core
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/requestcache.py", line 146, in _on_timeout
    cache.on_timeout()
  File "/home/sandip/tudelft/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/caches.py", line 20, in on_timeout
    self.circuit.state, self.circuit.sock_addr)
exceptions.AttributeError: 'Circuit' object has no attribute 'sock_addr'
```

**Comment by devos50** [comment]
We need to resolve this before we can update the IPv8 pointer (to add the DHT to Tribler) 👍
