### ISSUE TITLE
TestTunnelCommunity.test_tunnel_data error

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#278]
```
======================================================================
 ipv8/test/messaging/anonymization/test_community.py:TestTunnelCommunity
======================================================================
Check if 1 hop circuit
Check if circuit creation is
Check if 1 hop circuit
Check if multiple 1 hop
Check if the correct circuit
Check if a 2 hop
Check if a 2 hop
Check if a 2 hop
Check if introduction requests share
Check if two nodes don't
Check if two nodes can
Check if a three hop
Check if data is correctly
======================================================================    
FAIL: Check if data is
----------------------------------------------------------------------    
Traceback (most recent call last):
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1386, in
result = g.send(result)  
File "C:\workspace\jenkins2\workspace\ipv8\test_ipv8_PR_unittests_windows\ipv8\test\messaging\anonymization\test_community.py", line 245, in
self.assertEqual(len(ep_listener.received_packets), 1)   
File "c:\python27\lib\site-packages\twisted\trial\_synctest.py", line 432, in
super(_Assertions, self).assertEqual(first, second, msg) 
File "c:\python27\lib\unittest\case.py", line 513, in
assertion_func(first, second, msg=msg)  
File "c:\python27\lib\unittest\case.py", line 506, in
raise self.failureException(msg)   
FailTest: 0 != 1 
-------------------- >> begin captured logging
TunnelCommunity: DEBUG: Launching TunnelCommunity with
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode
TunnelCommunity: DEBUG: Launching TunnelCommunity with
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode
UDPEndpoint: DEBUG: Listening at 8080
TunnelCommunity: INFO: Want 1 data
TunnelCommunity: INFO: Creating a new
TunnelCommunity: INFO: First hop is
RequestCache: DEBUG: add <CircuitRequestCache anon-circuit-487366764>
TunnelCommunity: INFO: Creating circuit 487366764
TunnelCommunity: DEBUG: Got create (487366764)
TunnelCommunity: INFO: TunnelCommunity: we joined
RequestCache: DEBUG: add <CreatedRequestCache anon-created-487366764>
TunnelCommunity: DEBUG: Got created (487366764)
TunnelCommunity: DEBUG: Got data (487366764)
TunnelCommunity: DEBUG: Got data (487366764)
TunnelCommunity: DEBUG: Data for circuit
--------------------- >> end captured logging
```

**Comment by qstokkink** [comment]
Seems to be fixed by #301.
