### ISSUE TITLE
TestTunnelCommunity.test_three_hop_circuit tearDown error

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#290]
```
======================================================================
 ipv8/test/messaging/anonymization/test_community.py:TestTunnelCommunity
======================================================================
Check if 1 hop circuit
Check if circuit creation is
Check if 1 hop circuit
Check if multiple 1 hop
Check if the correct circuit
Check if a 2 hop
Check if a 2 hop
Check if a 2 hop
Check if introduction requests share
Check if two nodes don't
Check if two nodes can
Check if a three hop
======================================================================    
ERROR: Check if a three
----------------------------------------------------------------------    
Traceback (most recent call last):
File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 150, in
result = f(*args, **kw) 
File "c:\python27\lib\site-packages\twisted\internet\utils.py", line 201, in
reraise(exc_info[1], exc_info[2])   
File "c:\python27\lib\site-packages\twisted\internet\utils.py", line 197, in
result = f(*a, **kw) 
File "C:\workspace\jenkins2\workspace\ipv8\test_ipv8_PR_unittests_windows\ipv8\test\messaging\anonymization\test_community.py", line 27, in
super(TestTunnelCommunity, self).tearDown()   
File "C:\workspace\jenkins2\workspace\ipv8\test_ipv8_PR_unittests_windows\ipv8\test\base.py", line 61, in
node.unload()    
File "C:\workspace\jenkins2\workspace\ipv8\test_ipv8_PR_unittests_windows\ipv8\test\mocking\ipv8.py", line 51, in
self.overlay.unload()    
File "C:\workspace\jenkins2\workspace\ipv8\test_ipv8_PR_unittests_windows\ipv8\messaging\anonymization\community.py", line 206, in
self.remove_relay(circuit_id, 'unload', remove_now=True, destroy=True, both_sides=False)
File "C:\workspace\jenkins2\workspace\ipv8\test_ipv8_PR_unittests_windows\ipv8\messaging\anonymization\community.py", line 408, in
self.destroy_relay(to_remove, got_destroy_from=got_destroy_from)   
File "C:\workspace\jenkins2\workspace\ipv8\test_ipv8_PR_unittests_windows\ipv8\messaging\anonymization\community.py", line 469, in
self.relay_from_to[cid_from].peer.address) for cid_from in circuit_ids
File "C:\workspace\jenkins2\workspace\ipv8\test_ipv8_PR_unittests_windows\ipv8\messaging\anonymization\community.py", line 470, in
if cid_from in self.relay_from_to} 
KeyError: 1455200822L   
-------------------- >> begin captured logging
TunnelCommunity: DEBUG: Launching TunnelCommunity with
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode
TunnelCommunity: DEBUG: Launching TunnelCommunity with
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode
TunnelCommunity: DEBUG: Launching TunnelCommunity with
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode
TunnelCommunity: DEBUG: Launching TunnelCommunity with
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode
TunnelCommunity: INFO: Want 1 data
TunnelCommunity: INFO: Creating a new
TunnelCommunity: INFO: Look for a
RequestCache: DEBUG: add <CircuitRequestCache anon-circuit-21814555>
TunnelCommunity: INFO: Creating circuit 21814555
TunnelCommunity: DEBUG: Got create (21814555)
TunnelCommunity: INFO: TunnelCommunity: we joined
RequestCache: DEBUG: add <CreatedRequestCache anon-created-21814555>
TunnelCommunity: DEBUG: Got created (21814555)
TunnelCommunity: INFO: Extending circuit 21814555
TunnelCommunity: DEBUG: Got extend (21814555)
TunnelCommunity: INFO: On_extend send CREATE
TunnelCommunity: INFO: Extending circuit, got
RequestCache: DEBUG: add <ExtendRequestCache anon-circuit-3278061055>
TunnelCommunity: DEBUG: Got create (3278061055)
TunnelCommunity: INFO: TunnelCommunity: we joined
RequestCache: DEBUG: add <CreatedRequestCache anon-created-3278061055>
TunnelCommunity: DEBUG: Got created (3278061055)
TunnelCommunity: INFO: Got CREATED message
TunnelCommunity: DEBUG: Got extended (21814555)
TunnelCommunity: INFO: Extending circuit 21814555
TunnelCommunity: DEBUG: Got extend (21814555)
TunnelCommunity: DEBUG: Relay extend from
TunnelCommunity: DEBUG: Got extend (3278061055)
TunnelCommunity: INFO: On_extend send CREATE
TunnelCommunity: INFO: Extending circuit, got
RequestCache: DEBUG: add <ExtendRequestCache anon-circuit-1455200822>
TunnelCommunity: DEBUG: Got create (1455200822)
TunnelCommunity: INFO: TunnelCommunity: we joined
RequestCache: DEBUG: add <CreatedRequestCache anon-created-1455200822>
TunnelCommunity: DEBUG: Got created (1455200822)
TunnelCommunity: INFO: Got CREATED message
TunnelCommunity: DEBUG: Got extended (3278061055)
TunnelCommunity: DEBUG: Relay extended from
TunnelCommunity: DEBUG: Got extended (21814555)
TunnelCommunity: INFO: Removing circuit 21814555
TunnelCommunity: INFO: destroy_circuit 21814555 ('132.23.47.103',
TunnelCommunity: INFO: Removed circuit 21814555
RequestCache: DEBUG: Clearing <test_ipv8_PR_unittests_windows.ipv8.requestcache.RequestCache object
TunnelCommunity: INFO: Got destroy from
TunnelCommunity: INFO: Destroy_exit_socket 1455200822 ('164.232.194.223',
TunnelCommunity: INFO: Found relay 21814555
RequestCache: DEBUG: Clearing <test_ipv8_PR_unittests_windows.ipv8.requestcache.RequestCache object
TunnelCommunity: INFO: Fw destroy to
TunnelCommunity: INFO: Found relay 21814555
TunnelCommunity: INFO: Found relay 3278061055
TunnelCommunity: INFO: Got destroy from
TunnelCommunity: INFO: Removing relay 21814555
TunnelCommunity: INFO: Found relay 1455200822
TunnelCommunity: INFO: Fw destroy to
TunnelCommunity: INFO: Removing relay 3278061055
TunnelCommunity: INFO: Got destroy from
TunnelCommunity: INFO: Removing relay 21814555
TunnelCommunity: INFO: Fw destroy to
TunnelCommunity: INFO: Found relay 1455200822
TunnelCommunity: INFO: Removing relay 3278061055
TunnelCommunity: INFO: Found relay 3278061055
TunnelCommunity: INFO: Got destroy from
TunnelCommunity: INFO: Found relay 3278061055
RequestCache: DEBUG: Clearing <test_ipv8_PR_unittests_windows.ipv8.requestcache.RequestCache object
TunnelCommunity: INFO: Removing relay 1455200822
TunnelCommunity: INFO: Found relay 1455200822
TunnelCommunity: INFO: Found relay 3278061055
TunnelCommunity: INFO: Fw destroy to
TunnelCommunity: INFO: Removing relay 3278061055
TunnelCommunity: INFO: Got destroy from
TunnelCommunity: WARNING: Invalid or unauthorized
TunnelCommunity: INFO: Removing relay 3278061055
TunnelCommunity: INFO: Removing relay 1455200822
TunnelCommunity: INFO: Fw destroy to
TunnelCommunity: INFO: Removing relay 3278061055
TunnelCommunity: INFO: Removing relay 1455200822
--------------------- >> end captured logging
----------------------------------------------------------------------    
```

**Comment by qstokkink** [comment]
Seems to be fixed by #301.
