### ISSUE TITLE
IPv8 very slow to find peers

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#294]
This is a screenshot from Tribler running 30 seconds using the current `master` HEAD (f4dccad6e50e07b01a55b05b9fe0c09ada9deb58):

![afbeelding](https://user-images.githubusercontent.com/3630389/45927223-f8014100-bf2f-11e8-9b12-8255d2ebea08.png)

There are no peers at all, perhaps the IPv8 tracker is down?

Eventually after +- 2 minutes it starts finding peers though:
![afbeelding](https://user-images.githubusercontent.com/3630389/45927248-807fe180-bf30-11e8-85a8-8b6331c07046.png)

**Comment by qstokkink** [comment]
Actually, this is in the terminal:

```python
ERROR   1537700180.52                 community:717  (TriblerTunnelCommunity)  Exception occurred while handling packet!
Traceback (most recent call last):
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 714, in on_packet_from_circuit
    self.decode_map_private[data[22]](source_address, data, circuit_id)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 78, in wrapper
    return inner_wrapper(self, source_address, data)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/deprecated/lazy_community.py", line 109, in wrapper
    unpacked = self.serializer.unpack_to_serializables(payloads, data[23:])
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 297, in unpack_to_serializables
    serializable.optional_format_list, offset)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 231, in unpack_multiple
    unpacked, unpacked_size = self.unpack(format, data, current_offset)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 208, in unpack
    return self._packers[format].unpack_from(data, offset)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 87, in unpack_from
    out, = unpack_from('>%ds' % length, data, offset + self.format_size)
PackError: Failed to unserialize DataPayload
PackError: Could not unpack item 1: varlenH
error: unpack_from requires a buffer of at least 7496 bytes
```

**Comment by qstokkink** [comment]
@egbertbouman since you recently refactored: any thoughts on the stacktrace?

**Comment by qstokkink** [comment]
@devos50 also, this: https://jenkins-ci.tribler.org/job/Test_BootstrapServers/1931/

**Comment by qstokkink** [comment]
```
ERROR   1537712207.93                 community:722  (TriblerTunnelCommunity)  Exception occurred while handling packet!
Traceback (most recent call last):
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 719, in on_packet_from_circuit
    self.decode_map_private[msg_id](source_address, data, circuit_id)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 81, in wrapper
    return inner_wrapper(self, source_address, data)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/deprecated/lazy_community.py", line 114, in wrapper
    unpacked = self.serializer.unpack_to_serializables(payloads, data[23:])
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 299, in unpack_to_serializables
    sys.exc_info()[2])
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 295, in unpack_to_serializables
    serializable.optional_format_list, offset)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 241, in unpack_multiple
    sys.exc_info()[2])
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 233, in unpack_multiple
    unpacked, unpacked_size = self.unpack(format, data, current_offset)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 210, in unpack
    return self._packers[format].unpack_from(data, offset)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 90, in unpack_from
    out, = unpack_from('>%ds' % length, data, offset + self.format_size)
PackError: Failed to unserialize DataPayload
PackError: Could not pack item 1: varlenH
error: unpack_from requires a buffer of at least 27395 bytes

0002e9c27d9f3ba036bd25dd2068571f07f37bcfabf6069660af096b03
```

```
ERROR   1537712243.15                 community:722  (TriblerTunnelCommunity)  Exception occurred while handling packet!
Traceback (most recent call last):
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 719, in on_packet_from_circuit
    self.decode_map_private[msg_id](source_address, data, circuit_id)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 81, in wrapper
    return inner_wrapper(self, source_address, data)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/deprecated/lazy_community.py", line 114, in wrapper
    unpacked = self.serializer.unpack_to_serializables(payloads, data[23:])
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 299, in unpack_to_serializables
    sys.exc_info()[2])
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 295, in unpack_to_serializables
    serializable.optional_format_list, offset)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 241, in unpack_multiple
    sys.exc_info()[2])
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 233, in unpack_multiple
    unpacked, unpacked_size = self.unpack(format, data, current_offset)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 210, in unpack
    return self._packers[format].unpack_from(data, offset)
  File "/home/quinten/tribler/tribler/Tribler/pyipv8/ipv8/messaging/serialization.py", line 90, in unpack_from
    out, = unpack_from('>%ds' % length, data, offset + self.format_size)
PackError: Failed to unserialize DataPayload
PackError: Could not pack item 1: varlenH
error: unpack_from requires a buffer of at least 54279 bytes

0002e9c27d9f3ba036bd25dd2068571f07f37bcfabf606f2fa65a6d407
```

**Comment by qstokkink** [comment]
## OH

https://github.com/Tribler/py-ipv8/blob/02add669e7b768169b8e8d2f8555cba2e9b60c50/ipv8/messaging/anonymization/community.py#L899-L900

**Comment by devos50** [comment]
Right... so the packet is not parsed correctly?

**Comment by qstokkink** [comment]
@devos50 yes, it's trying to unpack a `DataPayload` from a serialized `PingPayload`, that kind of doesn't work.

**Comment by qstokkink** [comment]
Alright, I addressed the decoding in #296. On to the other half of this issue: bootstrap servers still seem to be dying: https://jenkins-ci.tribler.org/job/Test_BootstrapServers/1933/

**Comment by devos50** [comment]
Yes, it turns out that various of the machines running Dispersy tracker have no space left. I will clean them up.

@xoriole could you please install some triggers on the Dispersy trackers so we get a notification when they are running low on disk space?

**Comment by devos50** [comment]
I've restarted as many Dispersy trackers as possible, but hose1 is down. I've power cycled it but it takes some times before it's operational again. Most of them are up again (note that dispersy8 not responding is expected since that's an IPv8 tracker and does not respond to the newer IPv8 protocol):

![summary](https://user-images.githubusercontent.com/1707075/45929488-c8affb80-bf52-11e8-8a80-fc39b8904f77.png)

**Comment by qstokkink** [comment]
I guess that's good enough to close this issue?

**Comment by devos50** [comment]
Yup I think so.

**Comment by devos50** [comment]
hose1 is functional again.
