### ISSUE TITLE
TestTunnelCommunity.test_create_circuit error

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#297]
This was on the Mac tester:

```python
======================================================================
 ipv8/test/messaging/anonymization/test_community.py:TestTunnelCommunity
======================================================================
Check if 1 hop circuit creation works. ... FAIL

======================================================================
FAIL: Check if 1 hop circuit creation works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/Users/tribler/Documents/workspace2/workspace/ipv8/test_ipv8_mac/ipv8/test/messaging/anonymization/test_community.py", line 109, in test_create_circuit
    self.assertEqual(self.nodes[0].overlay.tunnels_ready(1), 1.0)
  File "/Library/Python/2.7/site-packages/twisted/trial/_synctest.py", line 425, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 515, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 508, in _baseAssertEqual
    raise self.failureException(msg)
FailTest: 0.0 != 1.0
-------------------- >> begin captured logging << --------------------
TunnelCommunity: DEBUG: Launching TunnelCommunity with prefix 00024d9b5c945540c9f59c22ff6a48153a2de6f53df7.
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode = False
TunnelCommunity: DEBUG: Launching TunnelCommunity with prefix 00024d9b5c945540c9f59c22ff6a48153a2de6f53df7.
TunnelCommunity: INFO: TunnelCommunity: setting become_exitnode = False
TunnelCommunity: INFO: Want 1 data circuits of length 1
TunnelCommunity: INFO: Creating a new circuit of length 1 (type: DATA)
TunnelCommunity: INFO: First hop is required exit
RequestCache: DEBUG: add <CircuitRequestCache anon-circuit-4242463319>
TunnelCommunity: INFO: Creating circuit 4242463319 of 1 hops. First hop: 7.220.46.206:8446
TunnelCommunity: DEBUG: Got create (4242463319) from ('136.142.230.138', 7973), I am Peer<7.220.46.206:8446, SwwF1XJ7HdXcohEU8y97qpPdHcQ=>
TunnelCommunity: INFO: TunnelCommunity: we joined circuit 4242463319 with neighbour ('136.142.230.138', 7973)
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.239s

FAILED (failures=1)
```

**Comment by qstokkink** [comment]
Seems to be fixed by #301.
