### ISSUE TITLE
AlreadyQuit error

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#299]
Got this in the tests:

```python
..............Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/quinten/tribler/py-ipv8/ipv8/messaging/interfaces/endpoint.py", line 56, in notify_listeners
    reactor.callInThread(self._deliver_later, listener, packet)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1064, in callInThread
    self.getThreadPool().callInThread(_callable, *args, **kwargs)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 211, in callInThread
    self.callInThreadWithCallback(None, func, *args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 269, in callInThreadWithCallback
    self._team.do(inContext)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 165, in do
    self._quit.check()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 46, in check
    raise AlreadyQuit()
twisted._threads._ithreads.AlreadyQuit: 

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/home/quinten/tribler/py-ipv8/ipv8/messaging/interfaces/endpoint.py", line 56, in notify_listeners
    reactor.callInThread(self._deliver_later, listener, packet)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/base.py", line 1064, in callInThread
    self.getThreadPool().callInThread(_callable, *args, **kwargs)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 211, in callInThread
    self.callInThreadWithCallback(None, func, *args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 269, in callInThreadWithCallback
    self._team.do(inContext)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 165, in do
    self._quit.check()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 46, in check
    raise AlreadyQuit()
twisted._threads._ithreads.AlreadyQuit:
```

Possibly related to this removal:
https://github.com/Tribler/py-ipv8/commit/946da2eff3a8784a7575d78a8dae2509cbee1e00#diff-1450657e30b530c7d1c87291cd1a687dL37

**Comment by qstokkink** [comment]
Definitely related to the removal. When I added the `reactor.running` check again, it errored out:

```python
if reactor.runninng and socket_address in internet:
    reactor.callInThread(internet[socket_address].notify_listeners, (self.wan_address, packet))
else:
    raise AssertionError("Received data from unregistered address %s" % repr(socket_address))
```

```python
Traceback (most recent call last):
  File "/home/quinten/tribler/py-ipv8/ipv8/test/messaging/anonymization/test_community.py", line 99, in test_create_circuit
    yield self.introduce_nodes()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/quinten/tribler/py-ipv8/ipv8/test/base.py", line 152, in introduce_nodes
    node.overlay.walk_to(other.endpoint.wan_address)
  File "/home/quinten/tribler/py-ipv8/ipv8/deprecated/community.py", line 277, in walk_to
    self.endpoint.send(address, packet)
  File "/home/quinten/tribler/py-ipv8/ipv8/test/mocking/endpoint.py", line 40, in send
    raise AssertionError("Received data from unregistered address %s" % repr(socket_address))
AssertionError: Received data from unregistered address ('114.152.219.169', 42352)
```

Then I expanded to this block:

```python
if reactor.running:
	if socket_address in internet:
		reactor.callInThread(internet[socket_address].notify_listeners, (self.wan_address, packet))
	else:
		raise AssertionError("Received data from unregistered address %s" % repr(socket_address))
else:
	raise AssertionError("Sending data before reactor is running!!!")
```

And I got:

```
Traceback (most recent call last):
  File "/home/quinten/tribler/py-ipv8/ipv8/test/messaging/anonymization/test_community.py", line 99, in test_create_circuit
    yield self.introduce_nodes()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/quinten/tribler/py-ipv8/ipv8/test/base.py", line 152, in introduce_nodes
    node.overlay.walk_to(other.endpoint.wan_address)
  File "/home/quinten/tribler/py-ipv8/ipv8/deprecated/community.py", line 277, in walk_to
    self.endpoint.send(address, packet)
  File "/home/quinten/tribler/py-ipv8/ipv8/test/mocking/endpoint.py", line 43, in send
    raise AssertionError("Sending data before reactor is running!!!")
AssertionError: Sending data before reactor is running!!!
```

For some reason, the experiment has begun running without the reactor running.

**Comment by qstokkink** [comment]
This is apparently generally true for all `TestBase` inheritors. At the end of the `setUp()` the reactor is not running:

```
    def setUp(self):
        super(TestBase, self).setUp()
        TestBase.__lockup_timestamp__ = time.time()

        from twisted.internet import reactor
        assert reactor.running
```

```
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/quinten/tribler/py-ipv8/ipv8/test/base.py", line 59, in setUp
    assert reactor.running
AssertionError
```

**Comment by qstokkink** [comment]
Hmm.. this is a difficult one, Twisted trial works like this:

```
d.addBoth(append)
if results:
	# d might have already been fired, in which case append is
	# called synchronously. Avoid any reactor stuff.
	return
[ ... ]
try:
	reactor.run()
```

In other words, the reactor starts running after the `setUp()`: unless its a Deferred. This conflicts with our tests, which were written to do `setUp()` using the reactor.
