### ISSUE TITLE
TrustChain tests unstable

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#37]
For some reason the Mac tests for TrustChain are unstable. This may have to do with a different `commit` protocol on Mac.

UPDATE: There seems to be a race condition in the test, also reproduced on Ubuntu 16.10.
Ran the following to produce:
```bash
#!/bin/bash
export PYTHONPATH=.
while $(nosetests test/attestation/trustchain/)
do
    echo ""
done
```
```python
======================================================================
FAIL: Check if missing blocks are retrieved through a crawl request.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/home/quinten/tribler/py-ipv8/test/util.py", line 125, in errback
    failure.raiseException()
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/home/quinten/tribler/py-ipv8/test/attestation/trustchain/test_community.py", line 229, in test_retrieve_missing_block
    self.assertEqual(self.nodes[node_nr].overlay.persistence.get(his_pubkey, 1).link_sequence_number, 1)
  File "/home/quinten/.local/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 432, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
FailTest: 2 != 1
-------------------- >> begin captured logging << --------------------
twisted: INFO: --> test.attestation.trustchain.test_community.TestTrustChainCommunity.test_retrieve_missing_block <--
TrustChainDB: DEBUG: loading database [:memory:]
TrustChainDB: DEBUG: TrustChain database path: :memory:
TrustChainDB: DEBUG: open database [:memory:]
TrustChainDB: DEBUG: PRAGMA page_size = 8192 (previously: 1024) [:memory:]
TrustChainDB: DEBUG: PRAGMA journal_mode = MEMORY (no change) [:memory:]
TrustChainDB: DEBUG: PRAGMA synchronous = NORMAL (previously: 2) [:memory:]
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: The trustchain community started with Public Key: 4c69624e61434c504b3a56aa579d3ca2b931de20b71a50882643378309b95095633667cccee32bb1ed0af52876c04964339034d9f610d1a3994b4b01153e5cec670efb8049cff999fe3d
TrustChainDB: DEBUG: loading database [:memory:]
TrustChainDB: DEBUG: TrustChain database path: :memory:
TrustChainDB: DEBUG: open database [:memory:]
TrustChainDB: DEBUG: PRAGMA page_size = 8192 (previously: 1024) [:memory:]
TrustChainDB: DEBUG: PRAGMA journal_mode = MEMORY (no change) [:memory:]
TrustChainDB: DEBUG: PRAGMA synchronous = NORMAL (previously: 2) [:memory:]
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: The trustchain community started with Public Key: 4c69624e61434c504b3a67148d49f0e1d601147f6c9f1b5bc4c9d85095039b554d06b1d14a99fd0bd7213a6137048a89b167e45b00ca830a9c2077f99f21b1e6ed929cc3d19802e7d6c7
TrustChainCommunity: INFO: Signed block to 02e7d6c7 (Block c7580377 from ...f999fe3d:1 links ...02e7d6c7:0 for {}) validation result (<function partial_next at 0x7f91bfb339b0>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to Peer<1.28.122.61:37216, O4TnSGduJ5QEF4dL/m8XPKSl9j8=> (Block c7580377 from ...f999fe3d:1 links ...02e7d6c7:0 for {})
TrustChainCommunity: INFO: Signed block to 02e7d6c7 (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {}) validation result (<function partial_next at 0x7f91bfb339b0>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to Peer<1.28.122.61:37216, O4TnSGduJ5QEF4dL/m8XPKSl9j8=> (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Block validation result <function no_info at 0x7f91bfb33aa0>, [], (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Block validation result <function no_info at 0x7f91bfb33aa0>, [], (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: INFO: Received request block addressed to us (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: INFO: Request block could not be validated sufficiently, crawling requester. (<function no_info at 0x7f91bfb33aa0>, [])
RequestCache: DEBUG: add <CrawlRequestCache crawl-81589634>
TrustChainCommunity: INFO: Requesting crawl of node f999fe3d:1 with id 81589634
TrustChainCommunity: INFO: Received crawl request from node 02e7d6c7 for sequence number 1
TrustChainCommunity: DEBUG: Sending block for crawl request to Peer<1.28.122.61:37216, O4TnSGduJ5QEF4dL/m8XPKSl9j8=> (Block c7580377 from ...f999fe3d:1 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Sending block for crawl request to Peer<1.28.122.61:37216, O4TnSGduJ5QEF4dL/m8XPKSl9j8=> (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: INFO: Sent 2 blocks
TrustChainCommunity: DEBUG: Block validation result <function valid at 0x7f91bfb338c0>, [], (Block c7580377 from ...f999fe3d:1 links ...02e7d6c7:0 for {})
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Block validation result <function valid at 0x7f91bfb338c0>, [], (Block c7580377 from ...f999fe3d:1 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x7f91bfb339b0>, [], (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x7f91bfb339b0>, [], (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: INFO: Received request block addressed to us (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: INFO: Signed block to f999fe3d (Block c4639c16 from ...02e7d6c7:1 links ...f999fe3d:2 for {}) validation result (<function partial_next at 0x7f91bfb339b0>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to Peer<156.112.38.66:56845, DTjdP/pkFJzvti2JZ7sXR8bVXWU=> (Block c4639c16 from ...02e7d6c7:1 links ...f999fe3d:2 for {})
TrustChainCommunity: DEBUG: Received already known block (Block c7580377 from ...f999fe3d:1 links ...02e7d6c7:0 for {})
TrustChainCommunity: INFO: Received request block addressed to us (Block c7580377 from ...f999fe3d:1 links ...02e7d6c7:0 for {})
TrustChainCommunity: INFO: Signed block to f999fe3d (Block 69209d79 from ...02e7d6c7:2 links ...f999fe3d:1 for {}) validation result (<function partial_next at 0x7f91bfb339b0>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to Peer<156.112.38.66:56845, DTjdP/pkFJzvti2JZ7sXR8bVXWU=> (Block 69209d79 from ...02e7d6c7:2 links ...f999fe3d:1 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x7f91bfb339b0>, [], (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x7f91bfb339b0>, [], (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block f490ad82 from ...f999fe3d:2 links ...02e7d6c7:0 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x7f91bfb339b0>, [], (Block c4639c16 from ...02e7d6c7:1 links ...f999fe3d:2 for {})
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x7f91bfb339b0>, [], (Block c4639c16 from ...02e7d6c7:1 links ...f999fe3d:2 for {})
TrustChainCommunity: DEBUG: Received already known block (Block c4639c16 from ...02e7d6c7:1 links ...f999fe3d:2 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x7f91bfb339b0>, [], (Block 69209d79 from ...02e7d6c7:2 links ...f999fe3d:1 for {})
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x7f91bfb339b0>, [], (Block 69209d79 from ...02e7d6c7:2 links ...f999fe3d:1 for {})
TrustChainCommunity: DEBUG: Received already known block (Block 69209d79 from ...02e7d6c7:2 links ...f999fe3d:1 for {})
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
```

**Comment by qstokkink** [comment]
Probably fixed by #35.
