### ISSUE TITLE
Mac TrustChain tests failing

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#40]
```
======================================================================
 test/attestation/trustchain/test_community.py:TestTrustChainCommunity
======================================================================
Test broadcasting a half block ... ok
Test broadcasting a half block pair ... ok
Check if a block can be crawled. ... ok
Check if the default crawl strategy produces blocks. ... ok
Check if a block can be crawled by negative range. ... ok
Check if blocks don't magically appear. ... ok
Check if a both halves of a fully signed block link to each other. ... ok
Check if blocks created in parallel will properly be stored in the database. ... ok
Check if missing blocks are retrieved through a crawl request. ... FAIL

======================================================================
FAIL: Check if missing blocks are retrieved through a crawl request.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/Library/Python/2.7/site-packages/twisted/internet/utils.py", line 201, in runWithWarningsSuppressed
    reraise(exc_info[1], exc_info[2])
  File "/Library/Python/2.7/site-packages/twisted/internet/utils.py", line 197, in runWithWarningsSuppressed
    result = f(*a, **kw)
  File "/Users/tribler/Documents/workspace/workspace/ipv8/test_ipv8_mac/test/util.py", line 125, in errback
    failure.raiseException()
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/Users/tribler/Documents/workspace/workspace/ipv8/test_ipv8_mac/test/attestation/trustchain/test_community.py", line 226, in test_retrieve_missing_block
    self.assertIsNotNone(self.nodes[node_nr].overlay.persistence.get(his_pubkey, 1))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 962, in assertIsNotNone
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Python/2.7/site-packages/twisted/trial/_synctest.py", line 368, in fail
    raise self.failureException(msg)
FailTest: unexpectedly None
-------------------- >> begin captured logging << --------------------
twisted: INFO: --> test_ipv8_mac.test.attestation.trustchain.test_community.TestTrustChainCommunity.test_retrieve_missing_block <--
TrustChainDB: DEBUG: loading database [:memory:]
TrustChainDB: DEBUG: TrustChain database path: :memory:
TrustChainDB: DEBUG: open database [:memory:]
TrustChainDB: DEBUG: PRAGMA page_size = 8192 (previously: 4096) [:memory:]
TrustChainDB: DEBUG: PRAGMA journal_mode = MEMORY (no change) [:memory:]
TrustChainDB: DEBUG: PRAGMA synchronous = NORMAL (previously: 2) [:memory:]
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: The trustchain community started with Public Key: 4c69624e61434c504b3a9774c700dd2bab1179c90a9ad454145177d3953a70832e8be75c36e4cdde846f0779fa63fd480cc169ec022825082068aeb8c0f48374ce6aef1a987d22325233
TrustChainDB: DEBUG: loading database [:memory:]
TrustChainDB: DEBUG: TrustChain database path: :memory:
TrustChainDB: DEBUG: open database [:memory:]
TrustChainDB: DEBUG: PRAGMA page_size = 8192 (previously: 4096) [:memory:]
TrustChainDB: DEBUG: PRAGMA journal_mode = MEMORY (no change) [:memory:]
TrustChainDB: DEBUG: PRAGMA synchronous = NORMAL (previously: 2) [:memory:]
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: The trustchain community started with Public Key: 4c69624e61434c504b3a30ae524d08c89b13a3fbb4bc93b880d2427014588a9b2011b0ef602cff8009434790236e887cd80ff5cc93c08ae1df095325421efff830c5626aab171f71fe53
TrustChainCommunity: INFO: Signed block to 1f71fe53 (Block 912e3938 from ...22325233:1 links ...1f71fe53:0 for {}) validation result (<function partial_next at 0x10d417e60>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to (215.136.3.36:40395) (Block 912e3938 from ...22325233:1 links ...1f71fe53:0 for {})
RequestCache: DEBUG: add <HalfBlockSignCache sign-18142001>
TrustChainCommunity: INFO: Signed block to 1f71fe53 (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {}) validation result (<function partial_next at 0x10d417e60>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to (215.136.3.36:40395) (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
RequestCache: DEBUG: add <HalfBlockSignCache sign-18142002>
TrustChainCommunity: DEBUG: Block validation result <function no_info at 0x10d417f50>, [], (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Block validation result <function no_info at 0x10d417f50>, [], (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: INFO: Received request block addressed to us (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: INFO: Request block could not be validated sufficiently, crawling requester. (<function no_info at 0x10d417f50>, [])
RequestCache: DEBUG: add <CrawlRequestCache crawl-95915699>
TrustChainCommunity: INFO: Requesting crawl of node 22325233:1 with id 95915699
TrustChainCommunity: INFO: Received crawl request from node 1f71fe53 for sequence number 1
TrustChainCommunity: DEBUG: Sending block for crawl request to Peer<215.136.3.36:40395, 34hUFsyOvKICXK8xv7aDqYDkPXE=> (Block 912e3938 from ...22325233:1 links ...1f71fe53:0 for {})
TrustChainCommunity: DEBUG: Sending block for crawl request to Peer<215.136.3.36:40395, 34hUFsyOvKICXK8xv7aDqYDkPXE=> (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: INFO: Sent 2 blocks
TrustChainCommunity: DEBUG: Block validation result <function valid at 0x10d417d70>, [], (Block 912e3938 from ...22325233:1 links ...1f71fe53:0 for {})
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Block validation result <function valid at 0x10d417d70>, [], (Block 912e3938 from ...22325233:1 links ...1f71fe53:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block 912e3938 from ...22325233:1 links ...1f71fe53:0 for {})
TrustChainCommunity: INFO: Received request block addressed to us (Block 912e3938 from ...22325233:1 links ...1f71fe53:0 for {})
TrustChainCommunity: INFO: Signed block to 22325233 (Block d4f8dfe3 from ...1f71fe53:1 links ...22325233:1 for {}) validation result (<function partial_next at 0x10d417e60>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to (1.47.221.125:16905) (Block d4f8dfe3 from ...1f71fe53:1 links ...22325233:1 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x10d417e60>, [], (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x10d417e60>, [], (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: INFO: Received request block addressed to us (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: INFO: Signed block to 22325233 (Block ab49fa5a from ...1f71fe53:2 links ...22325233:2 for {}) validation result (<function partial_next at 0x10d417e60>, [])
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Sending block to (1.47.221.125:16905) (Block ab49fa5a from ...1f71fe53:2 links ...22325233:2 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x10d417e60>, [], (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x10d417e60>, [], (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: DEBUG: Received already known block (Block 8dc82eb3 from ...22325233:2 links ...1f71fe53:0 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x10d417e60>, [], (Block d4f8dfe3 from ...1f71fe53:1 links ...22325233:1 for {})
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x10d417e60>, [], (Block d4f8dfe3 from ...1f71fe53:1 links ...22325233:1 for {})
TrustChainCommunity: DEBUG: Received already known block (Block d4f8dfe3 from ...1f71fe53:1 links ...22325233:1 for {})
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x10d417e60>, [], (Block ab49fa5a from ...1f71fe53:2 links ...22325233:2 for {})
TrustChainDB: DEBUG: commit [:memory:]
TrustChainCommunity: DEBUG: Block validation result <function partial_next at 0x10d417e60>, [], (Block ab49fa5a from ...1f71fe53:2 links ...22325233:2 for {})
TrustChainCommunity: DEBUG: Received already known block (Block ab49fa5a from ...1f71fe53:2 links ...22325233:2 for {})
--------------------- >> end captured logging << ---------------------
```

**Comment by qstokkink** [comment]
Fixed by #41 .
