### ISSUE TITLE
KeyError in Hidden services

### ISSUE THREAD

**Issue by xoriole** [Tribler/py-ipv8#420]
```python
ERROR   1548940024.29                 community:721  (TriblerTunnelTestnetCommunity)  Exception occurred while handling packet!
Traceback (most recent call last):
  File "Tribler\pyipv8\ipv8\messaging\anonymization\community.py", line 718, in on_packet_from_circuit
  File "Tribler\pyipv8\ipv8\messaging\anonymization\community.py", line 80, in wrapper
  File "Tribler\pyipv8\ipv8\lazy_community.py", line 104, in wrapper
  File "Tribler\pyipv8\ipv8\messaging\anonymization\community.py", line 78, in inner_wrapper
  File "Tribler\pyipv8\ipv8\messaging\anonymization\hidden_services.py", line 288, in on_create_e2e
KeyError: 'S1\xd0\x0c?\xf0+i\...\x94\x15\x0b'
```

**Comment by qstokkink** [comment]
@egbertbouman as this is your baby, do you want to take this issue?

**Comment by egbertbouman** [comment]
@qstokkink Sure, I'll take a look.
