### ISSUE TITLE
[TrustChain] writable buffers are not hashable

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#540]
```python
ERROR:TrustChainCommunity:Exception occurred while handling packet!
Traceback (most recent call last):
  File "/home/quinten/Documents/py-ipv8/ipv8/community.py", line 323, in on_packet
    self.decode_map[msg_id](source_address, data)
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/community.py", line 39, in wrapper
    return f(self, *args, **kwargs)
  File "/home/quinten/Documents/py-ipv8/ipv8/lazy_community.py", line 137, in wrapper
    return inner_wrapper(self, source_address, data)
  File "/home/quinten/Documents/py-ipv8/ipv8/lazy_community.py", line 104, in wrapper
    return func(self, source_address, *unpacked)
  File "/home/quinten/Documents/py-ipv8/ipv8/lazy_community.py", line 135, in inner_wrapper
    return func(inner_self, inner_source_address, *combo)
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/community.py", line 625, in received_crawl_response
    self.received_half_block(source_address, data[:-12])  # We cut off a few bytes to make it a BlockPayload
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/community.py", line 39, in wrapper
    return f(self, *args, **kwargs)
  File "/home/quinten/Documents/py-ipv8/ipv8/lazy_community.py", line 104, in wrapper
    return func(self, source_address, *unpacked)
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/community.py", line 296, in received_half_block
    self.process_half_block(block, peer).addErrback(lambda _: None)
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/community.py", line 39, in wrapper
    return f(self, *args, **kwargs)
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/community.py", line 370, in process_half_block
    validation = self.validate_persist_block(blk)
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/community.py", line 341, in validate_persist_block
    validation = block.validate(self.persistence)
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/block.py", line 167, in validate
    next_blk = database.get_block_after(self)
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/database.py", line 199, in get_block_after
    (block.sequence_number, database_blob(block.public_key)))
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/database.py", line 89, in _get
    return self.get_block_class(db_result[0])(db_result) if db_result else None
  File "/home/quinten/Documents/py-ipv8/ipv8/attestation/trustchain/database.py", line 53, in get_block_class
    if block_type not in self.block_types:
TypeError: writable buffers are not hashable
```

**Comment by qstokkink** [comment]
Seems like `db_result` should be cast to `six.binary_type(db_result)`.

**Comment by qstokkink** [comment]
This is actually quite messy, this is the output of printing the `repr(block_type)`, `str(block_type)` and `self.block_types`:

```
get_block_class 'tribler_bandwidth' tribler_bandwidth {'UNIVERSAL_BLOCK_LISTENER': <class 'ipv8.attestation.trustchain.block.TrustChainBlock'>}
get_block_class b'tribler_bandwidth' b'tribler_bandwidth' {'UNIVERSAL_BLOCK_LISTENER': <class 'ipv8.attestation.trustchain.block.TrustChainBlock'>}
```

Block types are `bytes`, sometimes checked as `unicode` and added to the block types as `unicode`.

**Comment by qstokkink** [comment]
This seems like the proper fix:

```patch
diff --git a/ipv8/attestation/trustchain/block.py b/ipv8/attestation/trustchain/block.py
index cd38294..ccb49fb 100644
--- a/ipv8/attestation/trustchain/block.py
+++ b/ipv8/attestation/trustchain/block.py
@@ -54,7 +54,7 @@ class TrustChainBlock(object):
              self.previous_hash, self.signature, self.timestamp, self.insert_time) = (data[0], data[2], data[3],
                                                                                       data[4], data[5], data[6],
                                                                                       data[7], data[8], data[9])
-            self.type = self.type if isinstance(self.type, bytes) else self.type.encode('utf-8')
+            self.type = self.type if isinstance(self.type, bytes) else str(self.type).encode('utf-8')
             self.public_key = self.public_key if isinstance(self.public_key, bytes) else binary_type(self.public_key)
             self.link_public_key = (self.link_public_key if isinstance(self.link_public_key, bytes)
                                     else binary_type(self.link_public_key))
diff --git a/ipv8/attestation/trustchain/community.py b/ipv8/attestation/trustchain/community.py
index 1a841c7..e0ee49b 100644
--- a/ipv8/attestation/trustchain/community.py
+++ b/ipv8/attestation/trustchain/community.py
@@ -47,7 +47,7 @@ class TrustChainCommunity(Community):
     master_peer = Peer(unhexlify("4c69624e61434c504b3a5730f52156615ecbcedb36c442992ea8d3c26b418edd8bd00e01dce26028cd"
                                  "1ebe5f7dce59f4ed59f8fcee268fd7f1c6dc2fa2af8c22e3170e00cdecca487745"))
 
-    UNIVERSAL_BLOCK_LISTENER = 'UNIVERSAL_BLOCK_LISTENER'
+    UNIVERSAL_BLOCK_LISTENER = b'UNIVERSAL_BLOCK_LISTENER'
     DB_CLASS = TrustChainDB
     DB_NAME = 'trustchain'
     version = b'\x02'
diff --git a/ipv8/attestation/trustchain/database.py b/ipv8/attestation/trustchain/database.py
index 81a84a8..6e55e9f 100644
--- a/ipv8/attestation/trustchain/database.py
+++ b/ipv8/attestation/trustchain/database.py
@@ -86,11 +86,11 @@ class TrustChainDB(Database):
 
     def _get(self, query, params):
         db_result = list(self.execute(self.get_sql_header() + query, params, fetch_all=False))
-        return self.get_block_class(db_result[0])(db_result) if db_result else None
+        return self.get_block_class(str(db_result[0]).encode('utf-8'))(db_result) if db_result else None
 
     def _getall(self, query, params):
         db_result = list(self.execute(self.get_sql_header() + query, params, fetch_all=True))
-        return [self.get_block_class(db_item[0])(db_item) for db_item in db_result]
+        return [self.get_block_class(str(db_item[0]).encode('utf-8'))(db_item) for db_item in db_result]
 
     def get(self, public_key, sequence_number):
         """
```

**Comment by ichorid** [comment]
For some reason, I'm  still seeing this. Py 2.7, latest devel. Submodules are updated.

**Comment by qstokkink** [comment]
@ichorid could you provide an up-to-date stacktrace?

**Comment by qstokkink** [comment]
Actually, since this issue was for Python 3: please provide the fresh stacktrace in a new issue so we can avoid confusion.

**Comment by xoriole** [comment]
Here is a stacktrace
```python
Traceback (most recent call last):
  File "/home/tribler/tudelft/tribler/Tribler/pyipv8/ipv8/community.py", line 326, in on_packet
    self.decode_map[msg_id](source_address, data)
  File "/home/tribler/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/community.py", line 39, in wrapper
    return f(self, *args, **kwargs)
  File "/home/tribler/tudelft/tribler/Tribler/pyipv8/ipv8/lazy_community.py", line 41, in wrapper
    return func(self, Peer(auth.public_key_bin, source_address), *unpacked)
  File "/home/tribler/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/community.py", line 546, in received_crawl_request
    blocks = self.persistence.crawl(payload.public_key, start_seq_num, end_seq_num, limit=10)
  File "/home/tribler/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py", line 279, in crawl
    return self.my_blocks_cache.get_range(start_seq_num, end_seq_num)
  File "/home/tribler/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/blockcache.py", line 40, in get_range
    blocks = [self.database.get_block_class(db_item[0])(db_item) for db_item in db_result]
  File "/home/tribler/tudelft/tribler/Tribler/pyipv8/ipv8/attestation/trustchain/database.py", line 53, in get_block_class
    if block_type not in self.block_types:
TypeError: writable buffers are not hashable
```

**Comment by qstokkink** [comment]
Seems like a different stacktrace. I'll move it to its own issue then.
