### ISSUE TITLE
Py3: Dictionary changed size 

### ISSUE THREAD

**Issue by ichorid** [Tribler/py-ipv8#555]
Current `devel`, Python3

```python
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/vader/src/TRIBLER/py37venv/lib/python3.7/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/vader/src/TRIBLER/py37venv/lib/python3.7/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/home/vader/src/TRIBLER/py37venv/lib/python3.7/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/vader/src/TRIBLER/py37venv/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/vader/src/TRIBLER/py37venv/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/vader/src/TRIBLER/Tribler/Tribler/pyipv8/ipv8/dht/community.py", line 480, in token_maintenance
    for node, (ts, _) in self.tokens.items():
builtins.RuntimeError: dictionary changed size during iteration

ERROR   1567604946.35            tribler_window:73   (root)  Traceback (most recent call last):
  File "/home/vader/src/TRIBLER/Tribler/TriblerGUI/event_request_manager.py", line 114, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Failure instance: Traceback: <class 'RuntimeError'>: dictionary changed size during iteration
/home/vader/src/TRIBLER/py37venv/lib/python3.7/site-packages/twisted/internet/base.py:1283:run
/home/vader/src/TRIBLER/py37venv/lib/python3.7/site-packages/twisted/internet/base.py:1292:mainLoop
/home/vader/src/TRIBLER/py37venv/lib/python3.7/site-packages/twisted/internet/base.py:913:runUntilCurrent
/home/vader/src/TRIBLER/py37venv/lib/python3.7/site-packages/twisted/internet/task.py:239:__call__
--- <exception caught here> ---
/home/vader/src/TRIBLER/py37venv/lib/python3.7/site-packages/twisted/internet/defer.py:151:maybeDeferred
/home/vader/src/TRIBLER/Tribler/Tribler/pyipv8/ipv8/dht/community.py:480:token_maintenance
]
```

**Comment by qstokkink** [comment]
`.items()` is a generator in Python 3, this should be cast to a `list()` copy before iterating over it. Also, we should check if the code inside can handle the source list being intermediately updated. @egbertbouman, as this is your code: do you want to look into this?

**Comment by qstokkink** [comment]
Already fixed on current master:

https://github.com/Tribler/py-ipv8/blob/ed53f62b4f732ca459e3b569185601acecfc39f7/ipv8/dht/community.py#L480

Please update your pointer in Tribler.
