### ISSUE TITLE
[py3] builtins.AttributeError: 'RuntimeError' object has no attribute 'message'

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#556]
Getting this error when simply running Tribler idle (with Python 3):

```
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/APIImplementation/LaunchManyCore.py", line 562, in sesscb_states_callback
    self.bootstrap.fetch_bootstrap_peers()
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/bootstrap.py", line 85, in fetch_bootstrap_peers
    self.dht.connect_peer(bytes(unhexlify(mid))).addCallbacks(on_success, on_failure)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/martijndevos/Documents/tribler/Tribler/Core/bootstrap.py", line 78, in on_failure
    self._logger.error("Failed to get DHT response:%s", failure.value.message)
builtins.AttributeError: 'RuntimeError' object has no attribute 'message'
```

The `message` attribute does not exist anymore.

**Comment by qstokkink** [comment]
Do we have an common way of stringifying Twisted Failures in Tribler?

**Comment by ichorid** [comment]
fixed in #4793

**Comment by ichorid** [comment]
I've done it with a simple `str` in my case. Works for both Pythons.

**Comment by qstokkink** [comment]
Thanks, I'll adhere to that then.
