### ISSUE TITLE
EndpointClosedException on Tribler shutown

### ISSUE THREAD

**Issue by ichorid** [Tribler/py-ipv8#566]
When closing Tribler (current `devel`, Python2):
```python
ERROR   1567946544.21              ipv8_service:148  (root)  Exception occurred while trying to walk!
Traceback (most recent call last):
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/pyipv8/ipv8_service.py", line 145, in on_tick
    strategy.take_step()
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/community/gigachannel/sync_strategy.py", line 21, in take_step
    self.overlay.send_random_to(peer)
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/community/gigachannel/community.py", line 86, in send_random_to
    self.endpoint.send(peer.address, self.ezr_pack(self.NEWS_PUSH_MESSAGE, RawBlobPayload(self.gossip_blob)))
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/pyipv8/ipv8/messaging/interfaces/udp/endpoint.py", line 42, in send
    self.assert_open()
  File "/home/vader/my_SRC/TRIBLER/tribler_ichorid/Tribler/pyipv8/ipv8/messaging/interfaces/udp/endpoint.py", line 78, in assert_open
    raise EndpointClosedException(self)
EndpointClosedException: <class 'ipv8.messaging.interfaces.udp.endpoint.UDPEndpoint'> is unexpectedly closed
```

**Comment by qstokkink** [comment]
This was fixed by #552, please update your pointer.

**Comment by ichorid** [comment]
I'm seeing it right now with the updated pointer. Please, recheck it yourself.

**Comment by devos50** [comment]
Could it be that the `send_random_to` is triggering while Tribler is closing? If so, IPv8 is most likely unloaded so the endpoint is not open anymore. We have seen issues of similar nature in the past when unloading communities.

Also, I think this issue is Tribler-related (at least Gigachannel related) so it should move to the Tribler repository.
