### ISSUE TITLE
builtins.ValueError: Invalid secret key (caused by libnacl 1.7)

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#632]
When running Tribler (or IPv8) with libnacl 1.7, I observe the following stack trace:

```
2019-12-12T10:20:49+0000 [twisted.internet.defer#critical] Unhandled error in Deferred:
2019-12-12T10:20:49+0000 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/noodle/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 74, in inner_wrapper
	    return func(inner_self, inner_source_address, *combo)
	  File "/home/noodle/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 749, in on_create
	    addCallback(self.should_join_circuit(payload, source_address), determined_to_join)
	  File "/home/noodle/tribler/Tribler/pyipv8/ipv8/util.py", line 76, in addCallback
	    return deferred.addCallbacks(callback, errback)
	  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 311, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/noodle/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 745, in determined_to_join
	    self.join_circuit(payload, source_address)
	  File "/home/noodle/tribler/Tribler/community/triblertunnel/community.py", line 458, in join_circuit
	    super(TriblerTunnelCommunity, self).join_circuit(create_payload, previous_node_address)
	  File "/home/noodle/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/community.py", line 717, in join_circuit
	    shared_secret, key, auth = self.crypto.generate_diffie_shared_secret(create_payload.key)
	  File "/home/noodle/tribler/Tribler/pyipv8/ipv8/messaging/anonymization/tunnelcrypto.py", line 47, in generate_diffie_shared_secret
	    AUTH = libnacl.crypto_auth(Y, shared_secret)
	  File "/home/noodle/.local/lib/python3.7/site-packages/libnacl/__init__.py", line 873, in crypto_auth
	    raise ValueError('Invalid secret key')
	builtins.ValueError: Invalid secret key
```

It works with libnacl 1.6.1. Digging a bit more into the changes that were made to libnacl, it turns out that [this commit](https://github.com/saltstack/libnacl/commit/53a6032cee524006bf1315f6f350ac56ef47f547) added various checks for the length of the shared secret. It seems that we are passing a 64 bytes string while libnacl expects a 32 bytes string.

@egbertbouman could you have a look at this?

**Comment by egbertbouman** [comment]
@devos50 Sure, will do.
