### ISSUE TITLE
RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#673]
On our bootstrap server:

```
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]: Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe... iteration',)>) at /opt/ipv8/ipv8/taskmanager.py:101
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]: handle: <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe... iteration',)>) at /opt/ipv8/ipv8/taskmanager.py:101>
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]: Traceback (most recent call last):
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:   File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:     self._callback(*self._args)
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:   File "/opt/ipv8/ipv8/taskmanager.py", line 104, in done_cb
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:     future.result()
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:   File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:     raise self._exception
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:     result = coro.send(None)
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:   File "/opt/ipv8/ipv8/taskmanager.py", line 13, in interval_runner
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:     await task(*args)
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:   File "/usr/lib/python3.5/asyncio/coroutines.py", line 210, in coro
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:     res = func(*args, **kw)
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:   File "scripts/tracker_plugin.py", line 38, in take_step
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]:     for peer in self.overlay.network.verified_peers:
Jan 18 14:10:26 ipv8-tracker-2 python3[10164]: RuntimeError: Set changed size during iteration
```

**Comment by qstokkink** [comment]
Aha, that is using the verified_peers raw. It should also claim the `self.overlay.network.graph_lock`.
