### ISSUE TITLE
KeyError when crawling large chains

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#676]
As seen in the TrustChain crawler:

```
Jan 21 15:49:05 trustchain-crawler python3[10614]: ERROR:asyncio:Task exception was never retrieved
Jan 21 15:49:05 trustchain-crawler python3[10614]: future: <Task finished coro=<TrustChainCommunity.send_next_partial_chain_crawl_request() done, defined at /opt/ipv8/ipv8/attestation/trustchain/community.py:491> exception=KeyError('chaincrawl:1139568000868646122288991920714046457696305908602')>
Jan 21 15:49:05 trustchain-crawler python3[10614]: Traceback (most recent call last):
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 532, in send_next_partial_chain_crawl_request
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.perform_partial_chain_crawl(cache, start, stop)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 489, in perform_partial_chain_crawl
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.send_next_partial_chain_crawl_request(cache)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 532, in send_next_partial_chain_crawl_request
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.perform_partial_chain_crawl(cache, start, stop)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 489, in perform_partial_chain_crawl
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.send_next_partial_chain_crawl_request(cache)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 532, in send_next_partial_chain_crawl_request
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.perform_partial_chain_crawl(cache, start, stop)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 489, in perform_partial_chain_crawl
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.send_next_partial_chain_crawl_request(cache)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 532, in send_next_partial_chain_crawl_request
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.perform_partial_chain_crawl(cache, start, stop)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 489, in perform_partial_chain_crawl
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.send_next_partial_chain_crawl_request(cache)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 524, in send_next_partial_chain_crawl_request
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.perform_partial_chain_crawl(cache, latest_block.sequence_number + 1, cache.known_chain_length)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 489, in perform_partial_chain_crawl
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.send_next_partial_chain_crawl_request(cache)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 524, in send_next_partial_chain_crawl_request
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.perform_partial_chain_crawl(cache, latest_block.sequence_number + 1, cache.known_chain_length)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 489, in perform_partial_chain_crawl
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.send_next_partial_chain_crawl_request(cache)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 524, in send_next_partial_chain_crawl_request
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.perform_partial_chain_crawl(cache, latest_block.sequence_number + 1, cache.known_chain_length)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 489, in perform_partial_chain_crawl
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.send_next_partial_chain_crawl_request(cache)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 524, in send_next_partial_chain_crawl_request
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.perform_partial_chain_crawl(cache, latest_block.sequence_number + 1, cache.known_chain_length)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 489, in perform_partial_chain_crawl
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.send_next_partial_chain_crawl_request(cache)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 524, in send_next_partial_chain_crawl_request
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.perform_partial_chain_crawl(cache, latest_block.sequence_number + 1, cache.known_chain_length)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 489, in perform_partial_chain_crawl
Jan 21 15:49:05 trustchain-crawler python3[10614]:     await self.send_next_partial_chain_crawl_request(cache)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/attestation/trustchain/community.py", line 499, in send_next_partial_chain_crawl_request
Jan 21 15:49:05 trustchain-crawler python3[10614]:     self.request_cache.pop("chaincrawl", cache.number)
Jan 21 15:49:05 trustchain-crawler python3[10614]:   File "/opt/ipv8/ipv8/requestcache.py", line 132, in pop
Jan 21 15:49:05 trustchain-crawler python3[10614]:     cache = self._identifiers.pop(identifier)
Jan 21 15:49:05 trustchain-crawler python3[10614]: KeyError: 'chaincrawl:1139568000868646122288991920714046457696305908602'
```

**Comment by egbertbouman** [comment]
I guess this is fixed by decorating `perform_partial_chain_crawl` with a `task` decorator, and removing the awaits when this function gets called.
