### ISSUE TITLE
struct.error: unpack_from requires a buffer of at least 80 bytes

### ISSUE THREAD

**Issue by ichorid** [Tribler/py-ipv8#701]
Latest Tribler `devel` just after starting:

```python
[PID:24757] 2020-03-13 17:30:46,432 - ERROR <community:334> DiscoveryCommunity.on_packet(): Exception occurred while handling packet!
Traceback (most recent call last):
  File "/home/tribler/src/pyipv8/ipv8/messaging/serialization.py", line 314, in unpack_multiple
    unpacked, unpacked_size = self.unpack(format, data, current_offset)
  File "/home/tribler/src/pyipv8/ipv8/messaging/serialization.py", line 291, in unpack
    return self._packers[format].unpack_from(data, offset)
  File "/home/tribler/src/pyipv8/ipv8/messaging/serialization.py", line 155, in unpack_from
    out, = unpack_from('>%ds' % length, data, offset + self.format_size)
struct.error: unpack_from requires a buffer of at least 80 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tribler/src/pyipv8/ipv8/messaging/serialization.py", line 341, in unpack_to_serializables
    serializable.optional_format_list, offset)
  File "/home/tribler/src/pyipv8/ipv8/messaging/serialization.py", line 321, in unpack_multiple
    type(e).__name__, str(e))) from e
ipv8.messaging.serialization.PackError: Could not pack item 1: varlenHx20
error: unpack_from requires a buffer of at least 80 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tribler/src/pyipv8/ipv8/community.py", line 329, in on_packet
    result = handler(source_address, data)
  File "/home/tribler/src/pyipv8/ipv8/lazy_community.py", line 33, in wrapper
    unpacked = self.serializer.ez_unpack_serializables(payloads, remainder[23:])
  File "/home/tribler/src/pyipv8/ipv8/messaging/serialization.py", line 360, in ez_unpack_serializables
    unpacked = self.unpack_to_serializables(serializables, data)
  File "/home/tribler/src/pyipv8/ipv8/messaging/serialization.py", line 344, in unpack_to_serializables
    type(e).__name__, str(e))) from e
ipv8.messaging.serialization.PackError: Failed to unserialize SimilarityResponsePayload
PackError: Could not pack item 1: varlenHx20
error: unpack_from requires a buffer of at least 80 bytes
```

**Comment by ichorid** [comment]
@qstokkink , @egbertbouman , could someone comment on this?

**Comment by qstokkink** [comment]
Is this a crash or log output?

I know some people are playing with the wire format, so getting garbage in from the network is expected. Crashing on it is unacceptable though.

**Comment by ichorid** [comment]
That's a log output.

**Comment by qstokkink** [comment]
That's fine then.
