### ISSUE TITLE
Embedded null character

### ISSUE THREAD

**Issue by ichorid** [Tribler/py-ipv8#714]
From Tribler Reporter 7.5.0-rc1:
```python
Traceback (most recent call last):
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
RuntimeError: Traceback (most recent call last):
File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
self._callback(*self._args)
File "ipv8/taskmanager.py", line 108, in done_cb
File "ipv8/messaging/anonymization/tunnel.py", line 131, in create_transport
File "ipv8/messaging/anonymization/tunnel.py", line 157, in sendto
ValueError: embedded null character
```

Looks like `socket.inet_aton(destination[0])` chokes on a malformed IP address. Should be trivial to fix.

**Comment by qstokkink** [comment]
We use `inet_aton` in quite a few places. We should make sure all of them are exception-handled.
