### ISSUE TITLE
IndexError: deque index out of range

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#721]
Observed this error on an exit node:

```
mrt 24 16:02:00 2057688 python3[12695]: Exception occurred while handling packet!
mrt 24 16:02:00 2057688 python3[12695]: Traceback (most recent call last):
mrt 24 16:02:00 2057688 python3[12695]:   File "/opt/tribler/src/pyipv8/ipv8/community.py", line 331, in on_packet
mrt 24 16:02:00 2057688 python3[12695]:     result = handler(source_address, data)
mrt 24 16:02:00 2057688 python3[12695]:   File "/opt/tribler/src/pyipv8/ipv8/lazy_community.py", line 39, in wrapper
mrt 24 16:02:00 2057688 python3[12695]:     return func(self, Peer(auth.public_key_bin, source_address), *unpacked)
mrt 24 16:02:00 2057688 python3[12695]:   File "/opt/tribler/src/pyipv8/ipv8/dht/community.py", line 444, in on_find_request
mrt 24 16:02:00 2057688 python3[12695]:     (payload.identifier, self.generate_token(node), values, nodes))
mrt 24 16:02:00 2057688 python3[12695]:   File "/opt/tribler/src/pyipv8/ipv8/dht/community.py", line 494, in generate_token
mrt 24 16:02:00 2057688 python3[12695]:     return hashlib.sha1(cast_to_bin(str(node)) + self.token_secrets[-1]).digest()
mrt 24 16:02:00 2057688 python3[12695]: IndexError: deque index out of range
```

**Comment by qstokkink** [comment]
Seems like dht magic, @egbertbouman want to look at this?

**Comment by egbertbouman** [comment]
@qstokkink Will do.

**Comment by qstokkink** [comment]
Thanks 👍
