### ISSUE TITLE
No address associated with hostname

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#726]
I'm not sure if this is an issue in the IPv8 core or not, but the error seems to be related to the DNS resolution in IPv8 (as reported by a user running Tribler 7.5 RC3):

```
Traceback (most recent call last):
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
RuntimeError: [Errno -5] No address associated with hostname
--LONG TEXT--
Traceback (most recent call last):
File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
File "ipv8/taskmanager.py", line 123, in done_cb
File "ipv8/messaging/anonymization/tunnel.py", line 166, in resolve
File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
socket.gaierror: [Errno -5] No address associated with hostname
--CONTEXT--
{'message': "Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...th hostname')>) at ipv8/taskmanager.py:120", 'exception': gaierror(-5, 'No address associated with hostname'), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...th hostname')>) at ipv8/taskmanager.py:120>}
```

@egbertbouman can you have a look at this one?

**Comment by qstokkink** [comment]
Seems we should try/except `OSError, ValueError` here:

https://github.com/Tribler/py-ipv8/blob/b330ca9b0ff2b9166765a12f6c72c20bfa601e38/ipv8/messaging/anonymization/tunnel.py#L166

**Comment by qstokkink** [comment]
On second thought, it should be caught here:

https://github.com/Tribler/py-ipv8/blob/b330ca9b0ff2b9166765a12f6c72c20bfa601e38/ipv8/messaging/anonymization/tunnel.py#L160

**Comment by qstokkink** [comment]
I'll handle this.
