### ISSUE TITLE
Issue when running Tribler

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#73]
When running Tribler using twistd, I suddenly got the following stack trace: 

```
Mar 14 14:18:35 tribler-runner1 twistd[1936]:         Traceback (most recent call last):
Mar 14 14:18:35 tribler-runner1 twistd[1936]:           File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1199, in run
Mar 14 14:18:35 tribler-runner1 twistd[1936]:             self.mainLoop()
Mar 14 14:18:35 tribler-runner1 twistd[1936]:           File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1208, in mainLoop
Mar 14 14:18:35 tribler-runner1 twistd[1936]:             self.runUntilCurrent()
Mar 14 14:18:35 tribler-runner1 twistd[1936]:           File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 828, in runUntilCurrent
Mar 14 14:18:35 tribler-runner1 twistd[1936]:             call.func(*call.args, **call.kw)
Mar 14 14:18:35 tribler-runner1 twistd[1936]:           File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in __call__
Mar 14 14:18:35 tribler-runner1 twistd[1936]:             d = defer.maybeDeferred(self.f, *self.a, **self.kw)
Mar 14 14:18:35 tribler-runner1 twistd[1936]:         --- <exception caught here> ---
Mar 14 14:18:35 tribler-runner1 twistd[1936]:           File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
Mar 14 14:18:35 tribler-runner1 twistd[1936]:             result = f(*args, **kw)
Mar 14 14:18:35 tribler-runner1 twistd[1936]:           File "/opt/tribler/Tribler/pyipv8/ipv8_service.py", line 108, in on_tick
Mar 14 14:18:35 tribler-runner1 twistd[1936]:             strategy.take_step(service)
Mar 14 14:18:35 tribler-runner1 twistd[1936]:           File "/opt/tribler/Tribler/pyipv8/ipv8/peerdiscovery/discovery.py", line 107, in take_step
Mar 14 14:18:35 tribler-runner1 twistd[1936]:             last_verified = self.under_construction[root][-1]
Mar 14 14:18:35 tribler-runner1 twistd[1936]:         exceptions.KeyError: <Tribler.pyipv8.ipv8.peer.Peer object at 0x7f53a4233e50>
```

**Comment by qstokkink** [comment]
Wait, what?

```python
for root in self.under_construction:
    last_verified = self.under_construction[root][-1]
```

**Comment by ichorid** [comment]
I've just seen this bug too.
Was doing a leecher->router->seeder test on my own isolated network.
The router was running all the time. I was manually starting and stopping the leecher. On the 3rd or 4th stop/start cycle, the router produced the following error:
```
INFO    1522835861.95       community:411   Removing exit socket 1362910478 no activity
2018-04-04 09:57:41+0000 [-] (UDP Port 44094 Closed)
2018-04-04 09:57:41+0000 [-] Stopping protocol <Tribler.pyipv8.ipv8.messaging.anonymization.tunnel.TunnelExitSocket object at 0x7f70f2280610>
INFO    1522835897.87       community:813   TunnelCommunity: we joined circuit 3519091886 with neighbour ('10.0.3.5', 28106)
INFO    1522835897.88       community:813   TunnelCommunity: we joined circuit 2586206496 with neighbour ('10.0.3.5', 28106)
INFO    1522835897.88       community:813   TunnelCommunity: we joined circuit 3712760453 with neighbour ('10.0.3.5', 28106)
INFO    1522835897.88       community:813   TunnelCommunity: we joined circuit 2157744986 with neighbour ('10.0.3.5', 28106)
INFO    1522835897.88       community:813   TunnelCommunity: we joined circuit 275454857 with neighbour ('10.0.3.5', 28106)
INFO    1522835897.89       community:813   TunnelCommunity: we joined circuit 3094025695 with neighbour ('10.0.3.5', 28106)
INFO    1522835897.89       community:813   TunnelCommunity: we joined circuit 3244526686 with neighbour ('10.0.3.5', 28106)
INFO    1522835897.89       community:813   TunnelCommunity: we joined circuit 3679805131 with neighbour ('10.0.3.5', 28106)
2018-04-04 09:58:18+0000 [-] TunnelExitSocket starting on 51636
2018-04-04 09:58:18+0000 [-] Starting protocol <Tribler.pyipv8.ipv8.messaging.anonymization.tunnel.TunnelExitSocket object at 0x7f70f6cdd5d0>
INFO    1522835931.95       community:411   Removing exit socket 275454857 no activity
2018-04-04 09:58:51+0000 [-] (UDP Port 51636 Closed)
2018-04-04 09:58:51+0000 [-] Stopping protocol <Tribler.pyipv8.ipv8.messaging.anonymization.tunnel.TunnelExitSocket object at 0x7f70f6cdd5d0>
2018-04-04 10:07:19+0000 [-] Unhandled error in Deferred:
2018-04-04 10:07:19+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
	    self.mainLoop()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/task.py", line 239, in __call__
	    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/mnt/router/tribler/Tribler/pyipv8/ipv8_service.py", line 109, in on_tick
	    strategy.take_step(service)
	  File "/mnt/router/tribler/Tribler/pyipv8/ipv8/peerdiscovery/discovery.py", line 107, in take_step
	    last_verified = self.under_construction[root][-1]
	exceptions.KeyError: <Tribler.pyipv8.ipv8.peer.Peer object at 0x7f70f4271d90>
```

**Comment by qstokkink** [comment]
@ichorid was this during shutdown?

**Comment by ichorid** [comment]
@qstokkink, no, the router was not shutting down when it happened. However, I was not able to shut it down by ctrl-c afterwards.

**Comment by qstokkink** [comment]
I'm assuming this was due to some exotic condition causing the `on_tick` calls to blend together. This should no longer be possible after the introduction of a `Lock` in `on_tick`. As such, this should be fixed now.
