### ISSUE TITLE
NoneType' object has no attribute 'number'

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#770]
As reported by a user running Tribler 7.5.0 (trace 33791):

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 112, in on_read_data
RuntimeError: 'NoneType' object has no attribute 'number'
--LONG TEXT--
Traceback (most recent call last):
File "ipv8\dht\community.py", line 388, in _contact_node
File "ipv8\dht\community.py", line 383, in _send_find_request
AttributeError: 'NoneType' object has no attribute 'number'
--CONTEXT--
{'message': 'Task exception was never retrieved', 'exception': AttributeError("'NoneType' object has no attribute 'number'"), 'future': <Task finished coro=<DHTCommunity._contact_node() done, defined at ipv8\dht\community.py:386> exception=AttributeError("'NoneType' object has no attribute 'number'")>}
```

**Comment by qstokkink** [comment]
Seems like a DHT error, @egbertbouman do you want to take this one?

**Comment by devos50** [comment]
I saw this one popping up very briefly during Tribler shutdown.
