### ISSUE TITLE
ValueError: Failed to auth msg

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#822]
**Operating System and version**
Windows 10, 64-bit

**Traceback and/or steps to reproduce**

I got this stack trace when running the Tribler application tester on Windows 10, 64-bit (mainnet).

```python
Traceback (most recent call last):
  File "ipv8\messaging\anonymization\community.py", line 664, in on_packet_from_circuit
  File "ipv8\messaging\anonymization\community.py", line 73, in wrapper
  File "ipv8\lazy_community.py", line 102, in wrapper
  File "ipv8\messaging\anonymization\community.py", line 71, in inner_wrapper
  File "ipv8\messaging\anonymization\community.py", line 745, in on_created
  File "src\tribler-core\tribler_core\modules\tunnel\community\triblertunnel_community.py", line 441, in _ours_on_created_extended
  File "ipv8\messaging\anonymization\community.py", line 522, in _ours_on_created_extended
  File "ipv8\messaging\anonymization\tunnelcrypto.py", line 46, in verify_and_generate_shared_secret
  File "lib\site-packages\libnacl\__init__.py", line 907, in crypto_auth_verify
ValueError: Failed to auth msg
```

**Comment by qstokkink** [comment]
Is this a crash or a log entry?

**Comment by devos50** [comment]
This is a log entry, not resulting in a hard crash but it seems to be affecting download speeds (since it might not be able to build the required circuits).

**Comment by qstokkink** [comment]
Just as a sanity check: this is not on testnet with an old community id?

**Comment by devos50** [comment]
No, they (were) running on the mainnet. Even if they would be running on testnet, the testnet exit nodes run the same code.

**Comment by qstokkink** [comment]
Alright thanks. This does not seem like a trivial fix then.

**Comment by qstokkink** [comment]
Possibly related to the failures in these Tribler tests? https://github.com/Tribler/tribler/commit/0d332d80e52ae3839d2e57fd75c75b21ee7bd3db

@egbertbouman you have dibs on errors in the TunnelCommunity: do you want to investigate?

**Comment by egbertbouman** [comment]
@qstokkink Sure, I'll have a look.

**Comment by qstokkink** [comment]
Thanks 👍

**Comment by devos50** [comment]
Download speeds on Windows 7, 64-bit (where this error did not show up):

![speed_down](https://user-images.githubusercontent.com/1707075/88156402-a7c99780-cc09-11ea-94d6-fe55265e5f1a.png)

Download speeds on Windows 10, 64-bit (where this error occurred):

![speed_down-2](https://user-images.githubusercontent.com/1707075/88156603-f1b27d80-cc09-11ea-9515-d50938c15d56.png)
