### ISSUE TITLE
Bits packer is inverted

### ISSUE THREAD

**Issue by qstokkink** [Tribler/py-ipv8#912]
**Operating System and version**
All.

**Traceback and/or steps to reproduce**

Add the following test to `test_serialization.py`:

```python
def test_pack_bits(self):
    values = [1, 0, 1, 0, 1, 0, 1, 0]

    packer = self.serializer.get_packer_for('bits')
    serialized = packer.pack(*values)

    unpack_list = []
    packer = self.serializer.get_packer_for('bits')
    packer.unpack(serialized, 0, unpack_list)

    self.assertEqual(values, unpack_list)
```

This will produce this traceback:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/quinten/.local/lib/python3.8/site-packages/asynctest/case.py", line 297, in run
    self._run_test_method(testMethod)
  File "/home/quinten/.local/lib/python3.8/site-packages/asynctest/case.py", line 352, in _run_test_method
    result = method()
  File "/home/quinten/Documents/py-ipv8/ipv8/test/messaging/test_serialization.py", line 228, in test_pack_bits
    self.assertEqual(values, unpack_list)
  File "/home/quinten/Downloads/pycharm-community-2019.3.3/plugins/python-ce/helpers/pycharm/teamcity/diff_tools.py", line 38, in _patched_equals
    raise error
Exception:  :: [1, 0, 1, 0, 1, 0, 1, 0] != [0, 1, 0, 1, 0, 1, 0, 1]
```

**Comment by qstokkink** [comment]
Seems like an easy fix.

`bit_7` used to be the left-most bit and the left-most argument. This was recently changed to `data[7]`, which is the right-most argument while still being the left-most bit:

https://github.com/Tribler/py-ipv8/commit/20212e3cd35c18ce14123fb61008faeffc418401#diff-5c4b900d904665bd3d6325b2cd3b34113554ae802b246d2ab941a8fd700dcb39R80-R96

Instead of packing `data[7] .. data[0]` we should simply pack `data[0] .. data[7]` and this should be resolved.
