### ISSUE TITLE
on_timeout required to be implemented?

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#917]
I have several request caches, most of which inherit from `NumberCache` or `RandomNumberCache`. For some of my caches, I wish to ignore the timeout and as such, I do not implement the `on_timeout` method. However, this gives me the following error:

```
Traceback (most recent call last):
  File "/Users/martijndevos/Documents/anydex-core/run_simulation.py", line 25, in <module>
    simulation.loop.run_forever()
  File "/Users/martijndevos/Documents/anydex-core/anydex/simulation/discrete_loop.py", line 45, in run_forever
    raise self._exc
  File "/Users/martijndevos/Documents/anydex-core/anydex/simulation/discrete_loop.py", line 111, in wrapper
    await coro
  File "/Users/martijndevos/Documents/anydex-core/py-ipv8/ipv8/taskmanager.py", line 24, in delay_runner
    await task(*args)
  File "/Users/martijndevos/Documents/anydex-core/py-ipv8/ipv8/util.py", line 35, in call_async
    return func(*args, **kwargs)
  File "/Users/martijndevos/Documents/anydex-core/py-ipv8/ipv8/requestcache.py", line 171, in _on_timeout
    cache.on_timeout()
  File "/Users/martijndevos/Documents/anydex-core/py-ipv8/ipv8/requestcache.py", line 57, in on_timeout
    raise NotImplementedError()
NotImplementedError
```

I wonder why it is required to implement this method. If there is a good reason for it, I suggest to make the `on_timeout` method abstract. Otherwise, I would not raise the exception.

**Comment by qstokkink** [comment]
I traced this logic back to this commit (from 9 years ago!): https://github.com/Tribler/dispersy/commit/2d3d5d4a4f8d9f91c10f0fd4d774a6c682eba9ae

This seems to have been implemented in a time that abstract base classes were cool and implemented everywhere, without any further reasoning.

I agree that for most caches silently timing out is more intuitive: a `pass` instead of `raise NotImplementedError()` seems like a more reasonable default.
