### ISSUE TITLE
IPv8 `types` implementation collides with the `types` packages in the Python standard libraries

### ISSUE THREAD

**Issue by devos50** [Tribler/py-ipv8#981]
**Operating System and version**
macOS Big Sur.

**Traceback and/or steps to reproduce**

Running a test with `pytest` using Pycharm:

```python
Testing started at 16:17 ...
/usr/local/bin/python3.9 /Applications/PyCharm.app/Contents/plugins/python/helpers/pycharm/_jb_pytest_runner.py --target test_assetamount.py::TestAssetAmount
Error processing line 1 of /usr/local/Cellar/protobuf/3.15.6/libexec/lib/python3.9/site-packages/protobuf-3.15.6-py3.9-nspkg.pth:

Error processing line 1 of /usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/homebrew-protobuf.pth:

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 169, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/martijndevos/Documents/anydex-core/py-ipv8/ipv8/types.py", line 1, in <module>
    import typing
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 23, in <module>
    import contextlib
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 6, in <module>
    from functools import wraps
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 22, in <module>
    from types import GenericAlias
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/Users/martijndevos/Documents/anydex-core/py-ipv8/ipv8/types.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 169, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 208, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 179, in addpackage
    import traceback
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 8, in <module>
    import functools
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 22, in <module>
    from types import GenericAlias
  File "/Users/martijndevos/Documents/anydex-core/py-ipv8/ipv8/types.py", line 1, in <module>
    import typing
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 23, in <module>
    import contextlib
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 6, in <module>
    from functools import wraps
ImportError: cannot import name 'wraps' from partially initialized module 'functools' (most likely due to a circular import) (/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 589, in <module>
    main()
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 576, in main
    known_paths = addsitepackages(known_paths)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 359, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 208, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site.py", line 179, in addpackage
    import traceback
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/traceback.py", line 5, in <module>
    import linecache
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/linecache.py", line 8, in <module>
    import functools
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py", line 22, in <module>
    from types import GenericAlias
  File "/Users/martijndevos/Documents/anydex-core/py-ipv8/ipv8/types.py", line 1, in <module>
    import typing
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 23, in <module>
    import contextlib
  File "/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 6, in <module>
    from functools import wraps
ImportError: cannot import name 'wraps' from partially initialized module 'functools' (most likely due to a circular import) (/usr/local/Cellar/python@3.9/3.9.2_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/functools.py)

Process finished with exit code 1

Empty suite

Empty suite

```

I suspect that the problem here is that the `types.py` provided by IPv8 collides with the `types` library in the standard library of Python 3. Note that the import process of `site` also tries to import `types` and it's picking the IPv8 one since IPv8 is on my `PYTHONPATH`. Removing `types.py` from IPv8 "resolves" the problem and make sure my tests run correctly. Maybe we could rename that file to avoid this collision?

**Comment by qstokkink** [comment]
> Note that the import process of `site` also tries to import `types` and it's picking the IPv8 one since IPv8 is on my `PYTHONPATH`.

This is indeed the problem. You really shouldn't have `/ipv8` in your `PYTHONPATH`.

Renaming types is only a superficial workaround, you'll eventually also hit `peer`, `util`, `loader`, etc. etc. There is no sane solution other than removing `/ipv8` from your `PYTHONPATH`.

Sadly, this is a limitation of the Python module naming/import system and something we can "fix".

**Comment by devos50** [comment]
Oh, it seems that I incorrectly marked my `ipv8` package as source, which definitely was wrong. Fixed it!
