### ISSUE TITLE
[7.9.0] TypeError: can only concatenate list (not "CancelledError") to list

### ISSUE THREAD

**Issue by drew2a** [Tribler/py-ipv8#993]
Sentry event: https://sentry.tribler.org/organizations/tribler/issues/686

```

Traceback (most recent call last):, 
  File "lib\asyncio\events.py", line 81, in _run, 
  File "ipv8\taskmanager.py", line 131, in done_cb, 
  File "ipv8\taskmanager.py", line 18, in interval_runner, 
  File "ipv8\messaging\anonymization\hidden_services.py", line 177, in do_peer_discovery, 
  File "ipv8\messaging\anonymization\tunnel.py", line 473, in lookup, 
TypeError: can only concatenate list (not "CancelledError") to list

```

**Comment by qstokkink** [comment]
Looks like a duplicate of #984. Could you confirm that IPv8 is at the latest version?

**Comment by drew2a** [comment]
Yes. It is a duplicate. But.. probably it is a good idea to add the ipv8 version to the Sentry event.
